[package]
name = "ene-tools-host"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ene-tool-host"
path = "src/main.rs"

[dependencies]
ene-tool-proto = { path = "../ene-tool-proto" }
ene-tools-utility = { path = "../ene-tools/utility" }
ene-tools-web = { path = "../ene-tools/web" }
ene-tools-app = { path = "../ene-tools/app" }
ene-tools-browser = { path = "../ene-tools/browser" }
ene-tools-fs = { path = "../ene-tools/fs" }
tokio = { workspace = true }
serde_json = { workspace = true }
