//! Integration tests for legacy VRM 0.x loading.
//!
//! Fixtures are generated by `tests/fixtures/gen_fixtures.py`; regenerate
//! after editing it with:
//!     python3 crates/ene-vrm/tests/fixtures/gen_fixtures.py
#![cfg_attr(
    test,
    expect(
        clippy::unwrap_used,
        clippy::expect_used,
        reason = "integration tests use unwrap/expect for assertions"
    )
)]

use std::path::PathBuf;

use ene_vrm::error::VrmError;
use ene_vrm::loader::load_vrm;
use ene_vrm::model::VrmFormatVersion;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Mirrors the in-crate helper: the GPU upload path needs a real device;
/// environments without a usable adapter yield None and skip the test.
fn try_create_wgpu_device() -> Option<(wgpu::Device, wgpu::Queue)> {
    pollster::block_on(async {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY,
            backend_options: wgpu::BackendOptions::default(),
            flags: wgpu::InstanceFlags::default(),
            display: None,
            memory_budget_thresholds: wgpu::MemoryBudgetThresholds::default(),
        });
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::LowPower,
                compatible_surface: None,
                force_fallback_adapter: true,
            })
            .await
            .ok()?;
        adapter
            .request_device(&wgpu::DeviceDescriptor {
                label: Some("ene-vrm-vrm0-test"),
                required_features: wgpu::Features::empty(),
                required_limits: {
                    let mut limits =
                        wgpu::Limits::downlevel_defaults().using_resolution(adapter.limits());
                    limits.max_bind_groups = adapter.limits().max_bind_groups;
                    limits
                },
                memory_hints: wgpu::MemoryHints::default(),
                experimental_features: wgpu::ExperimentalFeatures::disabled(),
                trace: wgpu::Trace::Off,
            })
            .await
            .ok()
    })
}

#[test]
fn minimal_vrm0_loads_with_expected_runtime_data() {
    let Some((device, queue)) = try_create_wgpu_device() else {
        return;
    };
    let model = load_vrm(fixture("minimal_vrm0.vrm"), &device, &queue).unwrap();

    assert_eq!(model.format_version(), VrmFormatVersion::V0x);
    assert_eq!(model.format_version_label(), "VRM 0.x");

    // Humanoid chain from the legacy array form.
    for bone in ["hips", "spine", "head", "leftUpperArm"] {
        assert!(
            model.humanoid.by_name(bone).is_some(),
            "missing humanoid bone {bone}"
        );
    }
    assert_eq!(model.humanoid.by_name("hips").unwrap().node, 0);
    assert_eq!(model.humanoid.by_name("head").unwrap().node, 2);
    assert_eq!(model.humanoid.by_name("leftUpperArm").unwrap().node, 3);

    // Legacy blendShape groups land as named expressions with node binds.
    let names: Vec<&str> = model
        .expressions_meta
        .iter()
        .map(|e| e.name.as_str())
        .collect();
    assert_eq!(
        names.len(),
        3,
        "expected exactly 3 expressions, got {names:?}"
    );
    for expected in ["joy", "sorrow", "blink"] {
        assert!(
            names.contains(&expected),
            "expression {expected} missing from {names:?}"
        );
    }
    let joy = model
        .expressions_meta
        .iter()
        .find(|e| e.name.as_str() == "joy")
        .unwrap();
    assert_eq!(joy.morph_target_binds.len(), 1);
    let bind = &joy.morph_target_binds[0];
    assert_eq!(bind.node, 5); // FaceMorphQuad node carries mesh 1
    assert_eq!(bind.index, 0);
    assert!((bind.weight - 0.9).abs() < 1e-6); // legacy 90% -> 0.9

    // Look-at offset and range map survive conversion.
    let look_at = model.look_at.as_ref().expect("lookAt should convert");
    let offset = look_at.offset_from_head_bone;
    assert!(
        (offset[0]).abs() < 1e-6
            && (offset[1] - 0.06).abs() < 1e-6
            && (offset[2] - 0.03).abs() < 1e-6
    );
    let inner = look_at.range_map.horizontal_inner;
    assert!((inner.input_max_value - 60.0).abs() < 1e-4);
    assert!((inner.output_scale - 8.0).abs() < 1e-4);

    // One two-joint spring-bone chain from secondaryAnimation.boneGroups.
    let spring_bones = model.spring_bones.as_ref().expect("spring bones");
    assert_eq!(spring_bones.springs.len(), 1);
    let chain = &spring_bones.springs[0];
    assert_eq!(chain.joints.len(), 2);
    assert_eq!(chain.joints[0].node, 6);
    assert_eq!(chain.joints[1].node, 7);
    assert!((chain.joints[0].stiffness - 4.0).abs() < 1e-5);
    assert_eq!(spring_bones.spec_version, "legacy-0.x");

    // MToon slots exist per material; material 0 comes from the legacy VRM block.
    assert_eq!(model.meshes.len(), 2);
    let mtoon0 = model.meshes[0].primitives[0]
        .mtoon
        .as_ref()
        .expect("material 0 should carry an MToon slot");
    assert!(!mtoon0.transparent_with_z_write);
    assert_eq!(mtoon0.render_queue_offset, 0);
}

#[test]
fn plain_gltf_without_vrm_extension_fails_as_not_vrm() {
    let Some((device, queue)) = try_create_wgpu_device() else {
        return;
    };
    let err = load_vrm(fixture("invalid_root_extension.vrm"), &device, &queue)
        .expect_err("fixture must fail");
    assert!(matches!(err, VrmError::NotVrm), "got {err:?}");
}

#[test]
fn unsupported_spec_version_fails_as_unsupported_format() {
    let Some((device, queue)) = try_create_wgpu_device() else {
        return;
    };
    let err =
        load_vrm(fixture("unsupported_spec.vrm"), &device, &queue).expect_err("fixture must fail");
    assert!(
        matches!(err, VrmError::UnsupportedFormat { .. }),
        "got {err:?}"
    );
}
