[package]
name = "ene-action"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
test-support = []

[dependencies]
ene-permission = { path = "../ene-permission" }
ene-primitive = { path = "../ene-primitive" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
