[package]
name = "ene-action"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ene-primitive = { path = "../ene-primitive" }
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
