use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::pin::Pin;
use std::sync::{Arc, Mutex, OnceLock};
use tokio_stream::{Stream, StreamExt};

use crate::error::LlmProviderError;
use crate::message::{LlmMessage, LlmResponseChunk};

/// Trait implemented by LLM providers to interface with Ene.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Returns the unique name of this provider.
    fn name(&self) -> &str;

    /// Initiates a chat completion stream with the given messages and tools.
    async fn create_chat_stream(
        &self,
        messages: &[LlmMessage],
        tools: &[ene_tool_proto::ToolSpec],
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<LlmResponseChunk, LlmProviderError>> + Send>>,
        LlmProviderError,
    >;

    /// Executes a non-streaming chat completion with optional JSON schema response.
    async fn chat_completion(
        &self,
        messages: &[LlmMessage],
        json_schema: Option<serde_json::Value>,
    ) -> Result<String, LlmProviderError>;
}

/// Collect a full assistant reply from a streaming chat completion.
///
/// OpenRouter and some OpenAI-compatible models respond reliably to streaming
/// requests but may hang or exceed budgets on non-streaming `chat().create()`.
pub async fn collect_chat_completion(
    provider: &dyn LlmProvider,
    messages: &[LlmMessage],
) -> Result<String, LlmProviderError> {
    let mut stream = provider.create_chat_stream(messages, &[]).await?;
    let mut content = String::new();
    while let Some(chunk_res) = stream.next().await {
        let chunk = chunk_res?;
        if let Some(delta) = chunk.text_delta {
            content.push_str(&delta);
        }
    }
    Ok(content)
}

/// Distinguishes embedding use cases. Providers may apply different prefixes
/// or chunking strategies per kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EmbeddingKind {
    /// Concise tool or document summary text.
    Summary,
    /// Full description text (often long).
    Description,
    /// One embedding per capability / action within a mega-tool.
    Capability,
    /// One embedding per worked example.
    Example,
    /// Negative-keyword text (used for soft penalties in Tool RAG).
    Negative,
    /// User query, may use a different prefix than documents.
    Query,
    /// Hypothetical document generated by `HyDE`.
    Hyde,
}

/// Errors raised by embedding providers. Wraps transport, provider, and
/// local-init errors in a single enum so call sites can use a typed error
/// instead of `String`. Consumers should match on the variant rather than
/// parsing the message.
#[derive(Debug, thiserror::Error)]
pub enum EmbeddingError {
    /// The embedding model failed to initialize (e.g. GGUF load error).
    /// Distinct from `Provider`, which is for transport / API errors.
    #[error("embedding init error: {0}")]
    Init(String),
    /// The provider returned a malformed or empty response, or a transport
    /// error (HTTP 4xx/5xx, network failure) prevented the request.
    #[error("embedding provider error: {0}")]
    Provider(String),
    /// The supplied text is empty or whitespace-only. We
    /// refuse to produce an embedding for it because
    /// every implementation would either return the
    /// zero vector (which has undefined cosine
    /// similarity and silently pollutes the store) or
    /// fall back to a placeholder that does not
    /// represent the input.
    #[error("empty or whitespace-only input; cannot produce a meaningful embedding")]
    EmptyInput,
}

/// Trait for generating vector embeddings from text (used by memory search and Tool RAG).
#[async_trait]
pub trait EmbeddingProvider: Send + Sync {
    /// Embed a single piece of text. The `kind` controls prefix strategy and
    /// chunking; providers are free to treat different kinds identically if
    /// their underlying model is prefix-agnostic.
    async fn embed(&self, text: &str, kind: EmbeddingKind) -> Result<Vec<f32>, EmbeddingError>;

    /// Embed a query. The default delegates to `embed(text, Query)`; override
    /// only if the provider has a different query prefix path.
    async fn embed_query(&self, text: &str) -> Result<Vec<f32>, EmbeddingError> {
        self.embed(text, EmbeddingKind::Query).await
    }

    /// Batch embed. Implementations should saturate hardware (thread pool for
    /// GGUF, concurrent HTTP for cloud). The default is a serial loop using
    /// `embed`; override for real performance.
    async fn embed_batch(
        &self,
        items: &[(&str, EmbeddingKind)],
    ) -> Result<Vec<Vec<f32>>, EmbeddingError> {
        let mut out = Vec::with_capacity(items.len());
        for (text, kind) in items {
            out.push(self.embed(text, *kind).await?);
        }
        Ok(out)
    }

    /// Hypothetical Document Embedding. The default echoes the query back;
    /// richer impls (LLM-backed) generate a hypothetical tool invocation.
    async fn hyde(&self, query: &str) -> Result<String, EmbeddingError> {
        Ok(query.to_string())
    }

    /// Returns true if this provider implements a native reranker (e.g. an LLM or cross-encoder).
    /// If false, callers may opt to skip `rerank()` and rely on retrieval scores.
    fn has_reranker(&self) -> bool {
        false
    }

    /// Rerank candidates by relevance to the query. The default uses
    /// embedding cosine similarity against `embed_query`; LLM-backed impls
    /// call a cheap model to score each (query, candidate) pair on a 0..1
    /// scale. Returned scores are aligned with `candidates` (same length).
    async fn rerank(
        &self,
        query: &str,
        candidates: &[ene_tool_proto::ToolSpec],
    ) -> Result<Vec<f32>, EmbeddingError> {
        let query_emb = self.embed_query(query).await?;
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        let mut batch_items = Vec::with_capacity(candidates.len());
        let texts: Vec<String> = candidates
            .iter()
            .map(|spec| format!("{} {}", spec.summary, spec.description))
            .collect();
        for text in &texts {
            batch_items.push((text.as_str(), EmbeddingKind::Description));
        }

        let embeddings = self.embed_batch(&batch_items).await?;
        let mut scores = Vec::with_capacity(embeddings.len());
        for emb in embeddings {
            scores.push(cosine_similarity(&query_emb, &emb));
        }
        Ok(scores)
    }

    /// The dimensionality of the embedding vectors produced by this provider.
    fn dimensions(&self) -> usize;
    /// A human-readable name identifying the embedding model.
    fn model_name(&self) -> &str;
}

/// Cosine similarity between two vectors. Returns 0.0 for empty or norm-zero
/// inputs. Both vectors must have the same length for a meaningful result.
#[must_use]
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.is_empty() || b.is_empty() || a.len() != b.len() {
        return 0.0;
    }
    let mut dot = 0.0_f64;
    let mut na = 0.0_f64;
    let mut nb = 0.0_f64;
    for (x, y) in a.iter().zip(b.iter()) {
        dot += f64::from(*x) * f64::from(*y);
        na += f64::from(*x).powi(2);
        nb += f64::from(*y).powi(2);
    }
    let denom = (na * nb).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        (dot / denom) as f32
    }
}

/// Factory trait to build specific `LlmProvider` instances from workspace configs.
pub trait LlmProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError>;
}

/// Global registry of `LlmProviderFactory` implementations.
pub struct LlmProviderRegistry {
    factories: Mutex<HashMap<String, Arc<dyn LlmProviderFactory>>>,
}

impl LlmProviderRegistry {
    /// Returns the static, thread-safe global registry instance.
    fn global() -> &'static Self {
        static REGISTRY: OnceLock<LlmProviderRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| Self {
            factories: Mutex::new(HashMap::new()),
        })
    }

    /// Registers a new provider factory.
    pub fn register(factory: Arc<dyn LlmProviderFactory>) {
        let name = factory.provider_name().to_string();
        if let Ok(mut guard) = Self::global().factories.lock() {
            guard.insert(name, factory);
        }
    }

    /// Tries to instantiate a provider by name using the registered factories.
    pub fn create_provider(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError> {
        let factory = {
            if let Ok(guard) = Self::global().factories.lock() {
                guard.get(name).cloned()
            } else {
                None
            }
        };

        match factory {
            Some(f) => f.create_provider(config),
            None => Err(LlmProviderError::Provider(format!(
                "No LlmProviderFactory registered for provider name: '{name}'"
            ))),
        }
    }
}
