use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::pin::Pin;
use std::sync::{Arc, Mutex, OnceLock};
use tokio_stream::Stream;

use crate::message::{LlmMessage, LlmResponseChunk};

/// Trait implemented by LLM providers to interface with Ene.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Returns the unique name of this provider.
    fn name(&self) -> &str;

    /// Initiates a chat completion stream with the given messages and tools.
    async fn create_chat_stream(
        &self,
        messages: &[LlmMessage],
        tools: &[ene_tool_proto::ToolSpec],
    ) -> Result<Pin<Box<dyn Stream<Item = Result<LlmResponseChunk, String>> + Send>>, String>;

    /// Executes a non-streaming chat completion with optional JSON schema response.
    async fn chat_completion(
        &self,
        messages: &[LlmMessage],
        json_schema: Option<serde_json::Value>,
    ) -> Result<String, String>;
}

/// Distinguishes embedding use cases. Providers may apply different prefixes
/// or chunking strategies per kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EmbeddingKind {
    /// Concise tool or document summary text.
    Summary,
    /// Full description text (often long).
    Description,
    /// One embedding per capability / action within a mega-tool.
    Capability,
    /// One embedding per worked example.
    Example,
    /// Negative-keyword text (used for soft penalties in Tool RAG).
    Negative,
    /// User query, may use a different prefix than documents.
    Query,
    /// Hypothetical document generated by `HyDE`.
    Hyde,
}

/// Errors raised by embedding providers. Wraps transport and provider errors
/// in a single enum so call sites can use a typed error instead of `String`.
#[derive(Debug, thiserror::Error)]
pub enum EmbeddingError {
    /// The provider returned a malformed or empty response.
    #[error("embedding provider error: {0}")]
    Provider(String),
    /// A batch or single request timed out.
    #[error("embedding timeout after {0:?}")]
    Timeout(std::time::Duration),
}

/// Trait for generating vector embeddings from text (used by memory search and Tool RAG).
#[async_trait]
pub trait EmbeddingProvider: Send + Sync {
    /// Embed a single piece of text. The `kind` controls prefix strategy and
    /// chunking; providers are free to treat different kinds identically if
    /// their underlying model is prefix-agnostic.
    async fn embed(&self, text: &str, kind: EmbeddingKind) -> Result<Vec<f32>, EmbeddingError>;

    /// Embed a query. The default delegates to `embed(text, Query)`; override
    /// only if the provider has a different query prefix path.
    async fn embed_query(&self, text: &str) -> Result<Vec<f32>, EmbeddingError> {
        self.embed(text, EmbeddingKind::Query).await
    }

    /// Batch embed. Implementations should saturate hardware (thread pool for
    /// GGUF, concurrent HTTP for cloud). The default is a serial loop using
    /// `embed`; override for real performance.
    async fn embed_batch(
        &self,
        items: &[(&str, EmbeddingKind)],
    ) -> Result<Vec<Vec<f32>>, EmbeddingError> {
        let mut out = Vec::with_capacity(items.len());
        for (text, kind) in items {
            out.push(self.embed(text, *kind).await?);
        }
        Ok(out)
    }

    /// Hypothetical Document Embedding. The default echoes the query back;
    /// richer impls (LLM-backed) generate a hypothetical tool invocation.
    async fn hyde(&self, query: &str) -> Result<String, EmbeddingError> {
        Ok(query.to_string())
    }

    /// Rerank candidates by relevance to the query. The default uses
    /// embedding cosine similarity against `embed_query`; LLM-backed impls
    /// call a cheap model to score each (query, candidate) pair on a 0..1
    /// scale. Returned scores are aligned with `candidates` (same length).
    async fn rerank(
        &self,
        query: &str,
        candidates: &[ene_tool_proto::ToolSpec],
    ) -> Result<Vec<f32>, EmbeddingError> {
        let query_emb = self.embed_query(query).await?;
        let mut scores = Vec::with_capacity(candidates.len());
        for spec in candidates {
            let text = format!("{} {}", spec.summary, spec.description);
            let emb = self.embed(&text, EmbeddingKind::Description).await?;
            scores.push(cosine_similarity(&query_emb, &emb));
        }
        Ok(scores)
    }

    /// The dimensionality of the embedding vectors produced by this provider.
    fn dimensions(&self) -> usize;
    /// A human-readable name identifying the embedding model.
    fn model_name(&self) -> &str;
}

/// Cosine similarity between two vectors. Returns 0.0 for empty or norm-zero
/// inputs. Both vectors must have the same length for a meaningful result.
#[must_use]
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.is_empty() || b.is_empty() || a.len() != b.len() {
        return 0.0;
    }
    let mut dot = 0.0_f64;
    let mut na = 0.0_f64;
    let mut nb = 0.0_f64;
    for (x, y) in a.iter().zip(b.iter()) {
        dot += f64::from(*x) * f64::from(*y);
        na += f64::from(*x).powi(2);
        nb += f64::from(*y).powi(2);
    }
    let denom = (na * nb).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        (dot / denom) as f32
    }
}

/// Factory trait to build specific `LlmProvider` instances from workspace configs.
pub trait LlmProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, String>;
}

/// Global registry of `LlmProviderFactory` implementations.
pub struct LlmProviderRegistry {
    factories: Mutex<HashMap<String, Arc<dyn LlmProviderFactory>>>,
}

impl LlmProviderRegistry {
    /// Returns the static, thread-safe global registry instance.
    fn global() -> &'static Self {
        static REGISTRY: OnceLock<LlmProviderRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| Self {
            factories: Mutex::new(HashMap::new()),
        })
    }

    /// Registers a new provider factory.
    pub fn register(factory: Arc<dyn LlmProviderFactory>) {
        let name = factory.provider_name().to_string();
        if let Ok(mut guard) = Self::global().factories.lock() {
            guard.insert(name, factory);
        }
    }

    /// Tries to instantiate a provider by name using the registered factories.
    pub fn create_provider(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, String> {
        let factory = {
            if let Ok(guard) = Self::global().factories.lock() {
                guard.get(name).cloned()
            } else {
                None
            }
        };

        match factory {
            Some(f) => f.create_provider(config),
            None => Err(format!(
                "No LlmProviderFactory registered for provider name: '{name}'"
            )),
        }
    }
}
