# https://git-cliff.org/docs/configuration

[changelog]
header = ""
body = """
{% if version %}\
## {{ version | trim_start_matches(pat="v") }}

{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^doc", group = "<!-- 2 -->Documentation" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactoring" },
  { message = "^test", group = "<!-- 5 -->Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "<!-- 6 -->Miscellaneous" },
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"

[bump]
features_always_bump_minor = false
breaking_commits_always_bump_major = false
