//! Typed memory domain model.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// The kind of a typed memory item.
///
/// Each memory has exactly one kind, which drives retrieval strategy
/// and lifecycle behaviour.
///
/// ## Per-kind policy table
///
/// Every aspect below is defined in code by an exhaustive `match` on this enum
/// (see [`MemoryKind::is_llm_extractable`], [`MemoryKind::is_contradiction_kind`],
/// [`MemoryKind::contradiction_key_match`], [`MemoryKind::has_diversification_base_slot`],
/// [`MemoryKind::is_recall_eligible`], [`MemoryKind::forgetting_policy`]), so a new
/// variant cannot be added without deciding each aspect — there are no
/// `matches!` / `_ =>` fallbacks that hide omissions. Consumers in `ene-mind`
/// (arbiter, diversification, recall, commitment ledger) route through these
/// methods rather than re-deriving the policy locally, keeping the definition
/// in this one place.
///
/// | Kind | LLM-extractable | Contradiction-checked | Contradiction key | Diversification base slot | Normal recall | Forgetting |
/// |---|---|---|---|---|---|---|
/// | Episodic | ✓ | — | — | ✓ | ✓ | standard |
/// | Semantic | ✓ | ✓ | vector (title embedding) | ✓ | ✓ | standard |
/// | `UserProfile` | ✓ | ✓ | vector (title embedding) | ✓ | ✓ | standard |
/// | Relationship | ✓ | ✓ | vector (title embedding) | — | ✓ | standard |
/// | Affective | ✓ | — | — | — | ✓ | standard |
/// | Commitment | ✓ | ✓ | vector (title embedding) | ✓ | ✓ | standard |
/// | Preference | ✓ | ✓ | vector (title embedding) | — | ✓ | standard |
/// | Procedure | ✓ | — | — | — | ✓ | standard |
/// | `WorldState` | — (reserved) | — | — | — | ✓ | standard |
/// | Reflection | ✓ | — | — | — | ✗ | standard |
///
/// **LLM-extractable** refers to the extractor's parse table
/// (`ene-mind/src/memory_writer/llm.rs`): the kinds the model may legitimately
/// produce. [`MemoryKind::WorldState`] is deliberately absent (see its variant
/// doc).
///
/// **Contradiction key** is the method used to decide two same-kind memories
/// talk about the same subject: *vector (title embedding)* compares
/// title embeddings by cosine similarity with an exact normalized-title
/// fallback when no embedder is available.
///
/// **Forgetting**: all kinds currently share the single global half-life
/// (`mind.memory.default_forgetting_half_life_days`); there is no
/// per-kind differentiation yet. Per-item `pinned` memories are exempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum MemoryKind {
    /// Specific events or conversations (what happened when).
    Episodic,
    /// Facts and general knowledge (what is true).
    Semantic,
    /// Information about the user's identity, background, and traits.
    UserProfile,
    /// Information about the relationship between the user and the companion.
    Relationship,
    /// Memories with strong emotional salience.
    Affective,
    /// Promises, tasks, and obligations the companion has made.
    Commitment,
    /// User likes, dislikes, and preferences.
    Preference,
    /// How-to knowledge and procedural instructions.
    Procedure,
    /// Observation of the user's environment/activity at a point in time.
    ///
    /// **Defined but unreachable today**: reserved for structured time-series
    /// world state and not yet generated by any producer. The LLM
    /// extractor deliberately rejects it (see [`MemoryKind::is_llm_extractable`])
    /// and no deterministic or tool producer emits it, so rows of this kind can
    /// only appear via direct store writes or future work.
    WorldState,
    /// Self-reflections by the companion about past interactions.
    Reflection,
}

/// How two memories of the same kind are keyed to the same subject for
/// contradiction checking.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ContradictionKeyMatch {
    /// Titles are compared by embedding cosine similarity, with an exact
    /// normalized-title fallback when no embedder is available.
    VectorTitle,
    /// This kind is not contradiction-checked (the key is never consulted).
    NotChecked,
}

/// Natural-forgetting treatment for a memory kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ForgettingPolicy {
    /// Standard decay using the global `default_forgetting_half_life_days`.
    ///
    /// Today every kind is `Standard` — no per-kind half-life exists yet. This
    /// variant is the extension point where a per-kind half-life would be
    /// introduced (as a new variant carrying the multiplier or override).
    Standard,
}

impl MemoryKind {
    /// Returns the `snake_case` string representation for storage/DB use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Episodic => "episodic",
            Self::Semantic => "semantic",
            Self::UserProfile => "user_profile",
            Self::Relationship => "relationship",
            Self::Affective => "affective",
            Self::Commitment => "commitment",
            Self::Preference => "preference",
            Self::Procedure => "procedure",
            Self::WorldState => "world_state",
            Self::Reflection => "reflection",
        }
    }

    /// Parse from a `snake_case` string, logging a warning on unrecognized values.
    pub fn from_db_str(s: &str) -> Self {
        match s {
            "episodic" => Self::Episodic,
            "semantic" => Self::Semantic,
            "user_profile" => Self::UserProfile,
            "relationship" => Self::Relationship,
            "affective" => Self::Affective,
            "commitment" => Self::Commitment,
            "preference" => Self::Preference,
            "procedure" => Self::Procedure,
            "world_state" => Self::WorldState,
            "reflection" => Self::Reflection,
            other => {
                tracing::error!(
                    other,
                    "unrecognized MemoryKind in DB, falling back to Semantic"
                );
                Self::Semantic
            }
        }
    }

    /// All defined variants in declaration order.
    ///
    /// Used by policy tables and by callers that must iterate every kind
    /// (diversification quotas, the LLM extractor schema, exhaustive tests).
    /// Keep in sync with the variant list when adding a kind.
    pub const ALL: [Self; 10] = [
        Self::Episodic,
        Self::Semantic,
        Self::UserProfile,
        Self::Relationship,
        Self::Affective,
        Self::Commitment,
        Self::Preference,
        Self::Procedure,
        Self::WorldState,
        Self::Reflection,
    ];

    /// Whether the LLM extractor may produce this kind (`memory_writer/llm.rs`
    /// parse table).
    ///
    /// [`Self::WorldState`] is deliberately not extractable: it is reserved for
    /// structured time-series world state and no producer exists yet, so
    /// an LLM candidate labelled `WorldState` hits the explicit rejection arm
    /// and falls back to Semantic with a warning rather than being silently
    /// produced.
    pub const fn is_llm_extractable(self) -> bool {
        match self {
            Self::Episodic
            | Self::Semantic
            | Self::UserProfile
            | Self::Relationship
            | Self::Affective
            | Self::Commitment
            | Self::Preference
            | Self::Procedure
            | Self::Reflection => true,
            Self::WorldState => false,
        }
    }

    /// Whether an incoming candidate of this kind is checked for contradictions
    /// against existing same-kind memories (`memory_writer/arbiter.rs`).
    ///
    /// The identity-like kinds (Semantic, `UserProfile`, Preference,
    /// Relationship) plus Commitment: a rephrased or updated commitment must
    /// supersede the prior record rather than accumulate. In the normal
    /// write path commitment candidates bypass the typed arbiter — the
    /// commitment ledger (`ene-mind/src/commitments/mod.rs`) enforces the same
    /// title-keyed update/cancel semantics as the source of truth; this entry
    /// is the typed-memory path's defense in depth.
    pub const fn is_contradiction_kind(self) -> bool {
        match self {
            Self::Semantic
            | Self::UserProfile
            | Self::Preference
            | Self::Relationship
            | Self::Commitment => true,
            Self::Episodic
            | Self::Affective
            | Self::Procedure
            | Self::WorldState
            | Self::Reflection => false,
        }
    }

    /// How the contradiction check keys two same-kind memories to the same
    /// subject. Only meaningful when [`Self::is_contradiction_kind`] is
    /// true.
    pub const fn contradiction_key_match(self) -> ContradictionKeyMatch {
        match self {
            Self::Semantic
            | Self::UserProfile
            | Self::Preference
            | Self::Relationship
            | Self::Commitment => ContradictionKeyMatch::VectorTitle,
            Self::Episodic
            | Self::Affective
            | Self::Procedure
            | Self::WorldState
            | Self::Reflection => ContradictionKeyMatch::NotChecked,
        }
    }

    /// Whether this kind reserves a guaranteed base slot in recall
    /// diversification (`ene-mind/src/recall/diversify.rs`). Kinds without a
    /// base slot still surface dynamically when they are relevant enough.
    pub const fn has_diversification_base_slot(self) -> bool {
        match self {
            Self::Semantic | Self::Episodic | Self::UserProfile | Self::Commitment => true,
            Self::Relationship
            | Self::Affective
            | Self::Preference
            | Self::Procedure
            | Self::WorldState
            | Self::Reflection => false,
        }
    }

    /// Whether this kind is eligible for normal (cognitive) recall.
    ///
    /// [`Self::Reflection`] is excluded: reflections are a scoring signal
    /// applied separately by the self-reflection pipeline, never context
    /// injected into the LLM.
    pub const fn is_recall_eligible(self) -> bool {
        match self {
            Self::Episodic
            | Self::Semantic
            | Self::UserProfile
            | Self::Relationship
            | Self::Affective
            | Self::Commitment
            | Self::Preference
            | Self::Procedure
            | Self::WorldState => true,
            Self::Reflection => false,
        }
    }

    /// Natural-forgetting treatment for this kind.
    ///
    /// Today every kind is [`ForgettingPolicy::Standard`]: the sweep applies a
    /// single global half-life (`mind.memory.default_forgetting_half_life_days`)
    /// to all kinds, with per-item `pinned` memories exempt. This exhaustive
    /// match is the extension point where a per-kind half-life would be
    /// introduced.
    pub const fn forgetting_policy(self) -> ForgettingPolicy {
        match self {
            Self::Episodic
            | Self::Semantic
            | Self::UserProfile
            | Self::Relationship
            | Self::Affective
            | Self::Commitment
            | Self::Preference
            | Self::Procedure
            | Self::WorldState
            | Self::Reflection => ForgettingPolicy::Standard,
        }
    }
}

/// The lifecycle status of a memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum MemoryStatus {
    /// Currently relevant and retrievable.
    Active,
    /// Decayed but still retrievable with lower priority.
    Faded,
    /// No longer shown in normal recall but preserved.
    Archived,
    /// User has disputed or corrected this memory.
    Disputed,
    /// Replaced by a newer, conflicting memory.
    Superseded,
    /// Explicitly deleted by the user.
    UserDeleted,
}

impl MemoryStatus {
    /// Returns the `snake_case` string representation for storage/DB use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Faded => "faded",
            Self::Archived => "archived",
            Self::Disputed => "disputed",
            Self::Superseded => "superseded",
            Self::UserDeleted => "user_deleted",
        }
    }

    /// Parse from a `snake_case` string, logging a warning on unrecognized values.
    pub fn from_db_str(s: &str) -> Self {
        match s {
            "active" => Self::Active,
            "faded" => Self::Faded,
            "archived" => Self::Archived,
            "disputed" => Self::Disputed,
            "superseded" => Self::Superseded,
            "user_deleted" => Self::UserDeleted,
            other => {
                tracing::error!(
                    other,
                    "unrecognized MemoryStatus in DB, falling back to Active"
                );
                Self::Active
            }
        }
    }
}

/// The scope or ownership of a memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum MemoryScope {
    /// Memory associated with the character/companion.
    Character,
    /// Memory associated with the user.
    User,
    /// Memory shared between character and user.
    Shared,
}

impl MemoryScope {
    /// Returns the `snake_case` string representation for storage/DB use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Character => "character",
            Self::User => "user",
            Self::Shared => "shared",
        }
    }

    /// Parse from a `snake_case` string, logging a warning on unrecognized values.
    pub fn from_db_str(s: &str) -> Self {
        match s {
            "character" => Self::Character,
            "user" => Self::User,
            "shared" => Self::Shared,
            other => {
                tracing::error!(
                    other,
                    "unrecognized MemoryScope in DB, falling back to Character"
                );
                Self::Character
            }
        }
    }
}

/// The provenance of a memory (how it was created).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum MemorySource {
    /// Extracted directly from conversation turns.
    Conversation,
    /// Explicitly stated by the user.
    UserStated,
    /// Extracted by an LLM-based extraction pipeline.
    LlmExtracted,
    /// Inferred by deterministic rules.
    Inferred,
    /// Imported from external data.
    Imported,
    /// Derived from `CCv3` character card data.
    Ccv3,
}

impl MemorySource {
    /// Returns the `snake_case` string representation for storage/DB use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Conversation => "conversation",
            Self::UserStated => "user_stated",
            Self::LlmExtracted => "llm_extracted",
            Self::Inferred => "inferred",
            Self::Imported => "imported",
            Self::Ccv3 => "ccv3",
        }
    }

    /// Parse from a `snake_case` string, logging a warning on unrecognized values.
    pub fn from_db_str(s: &str) -> Self {
        match s {
            "conversation" => Self::Conversation,
            "user_stated" => Self::UserStated,
            "llm_extracted" => Self::LlmExtracted,
            "inferred" => Self::Inferred,
            "imported" => Self::Imported,
            "ccv3" => Self::Ccv3,
            other => {
                tracing::error!(
                    other,
                    "unrecognized MemorySource in DB, falling back to Conversation"
                );
                Self::Conversation
            }
        }
    }
}

/// A normalised confidence score for a memory (0.0–1.0).
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MemoryConfidence(f32);

impl MemoryConfidence {
    /// The maximum possible confidence.
    pub const MAX: Self = Self(1.0);

    /// Create a new confidence value, clamping to [0.0, 1.0].
    ///
    /// NaN inputs are mapped to 0.5 (default).
    #[must_use]
    pub fn new(raw: f32) -> Self {
        let val = if raw.is_nan() {
            0.5
        } else {
            raw.clamp(0.0, 1.0)
        };
        Self(val)
    }

    /// Unwrap to the raw `f32` value.
    pub const fn get(self) -> f32 {
        self.0
    }
}

impl Default for MemoryConfidence {
    fn default() -> Self {
        Self(0.5)
    }
}

/// A normalised salience / importance score for a memory (0.0–1.0).
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MemorySalience(f32);

impl MemorySalience {
    /// The maximum possible salience.
    pub const MAX: Self = Self(1.0);

    /// Create a new salience value, clamping to [0.0, 1.0].
    ///
    /// NaN inputs are mapped to 0.5 (default).
    #[must_use]
    pub fn new(raw: f32) -> Self {
        let val = if raw.is_nan() {
            0.5
        } else {
            raw.clamp(0.0, 1.0)
        };
        Self(val)
    }

    /// Unwrap to the raw `f32` value.
    pub const fn get(self) -> f32 {
        self.0
    }
}

impl Default for MemorySalience {
    fn default() -> Self {
        Self(0.5)
    }
}

/// Affect / emotion annotation attached to a memory item.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct AffectAnnotation {
    /// Pleasure–displeasure (-1.0..=1.0).
    pub valence: f32,
    /// Excitement–calm (-1.0..=1.0).
    pub arousal: f32,
}

impl Default for AffectAnnotation {
    fn default() -> Self {
        Self {
            valence: 0.0,
            arousal: 0.0,
        }
    }
}

/// A typed memory item.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MemoryItem {
    /// Primary key (`None` until persisted).
    pub id: Option<i64>,
    /// Ownership scope.
    pub scope: MemoryScope,
    /// Character identifier.
    pub character_id: String,
    /// User identifier (may be empty).
    pub user_id: String,
    /// Memory kind.
    pub kind: MemoryKind,
    /// Short title or label.
    pub title: String,
    /// Full memory content.
    pub content: String,
    /// Provenance of the memory.
    pub source: MemorySource,
    /// Optional reference to the source (e.g. `session_id` or turn sequence).
    pub source_ref: Option<String>,
    /// Confidence score.
    pub confidence: MemoryConfidence,
    /// Salience / importance score.
    pub salience: MemorySalience,
    /// Emotional annotation (valence + arousal).
    pub affect: AffectAnnotation,
    /// Relationship impact score (-1.0..=1.0).
    pub relationship_impact: f32,
    /// Number of times this memory has been accessed.
    pub access_count: i64,
    /// Timestamp of the last access.
    pub last_accessed_at: Option<DateTime<Utc>>,
    /// When the memory was created.
    pub created_at: DateTime<Utc>,
    /// When the memory was last updated.
    pub updated_at: DateTime<Utc>,
    /// Start of validity period.
    pub valid_from: Option<DateTime<Utc>>,
    /// End of validity period.
    pub valid_until: Option<DateTime<Utc>>,
    /// Lifecycle status.
    pub status: MemoryStatus,
    /// ID of the memory this one supersedes (predecessor link).
    ///
    /// Set on replacement rows; `None` when this memory is not a superseding
    /// successor. Superseded rows do not populate this field.
    pub supersedes_id: Option<i64>,
    /// User-pinned memories are exempt from natural decay.
    #[serde(default)]
    pub pinned: bool,
    /// When the memory entered `faded` status (archive-decay anchor).
    #[serde(default)]
    pub faded_at: Option<DateTime<Utc>>,
    /// Optional FK to the commitment ledger row (`commitments.id`).
    #[serde(default)]
    pub commitment_id: Option<i64>,
}

/// Payload for creating a new memory item (fields set by the store are omitted).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewMemoryItem {
    /// Ownership scope.
    pub scope: MemoryScope,
    /// Character identifier.
    pub character_id: String,
    /// User identifier (may be empty).
    pub user_id: String,
    /// Memory kind.
    pub kind: MemoryKind,
    /// Short title or label.
    pub title: String,
    /// Full memory content.
    pub content: String,
    /// Provenance of the memory.
    pub source: MemorySource,
    /// Optional reference to the source.
    pub source_ref: Option<String>,
    /// Confidence score.
    pub confidence: MemoryConfidence,
    /// Salience / importance score.
    pub salience: MemorySalience,
    /// Emotional annotation.
    pub affect: AffectAnnotation,
    /// Relationship impact score.
    pub relationship_impact: f32,
    /// Start of validity period.
    pub valid_from: Option<DateTime<Utc>>,
    /// End of validity period.
    pub valid_until: Option<DateTime<Utc>>,
    /// Initial lifecycle status.
    pub status: MemoryStatus,
    /// ID of the memory this one supersedes.
    pub supersedes_id: Option<i64>,
    /// Pin state — pinned memories skip natural decay.
    #[serde(default)]
    pub pinned: bool,
    /// Optional created timestamp (defaults to now on insert).
    #[serde(default)]
    pub created_at: Option<DateTime<Utc>>,
    /// Optional FK to the commitment ledger row.
    #[serde(default)]
    pub commitment_id: Option<i64>,
}

/// Recall source that surfaced a memory candidate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum MemoryCandidateSource {
    /// Vector embedding similarity search.
    Vector,
    /// Lexical token overlap with query text.
    Lexical,
    /// Recent / active memory listing.
    Recent,
    /// Active companion commitment ledger.
    Commitment,
    /// Unconfirmed candidate awaiting user approval.
    ///
    /// Candidates the arbiter deferred with `AskConfirmationLater` live in the
    /// pending queue rather than the typed-memory table. They still compete in
    /// hybrid recall so the character can ask about them when the topic comes
    /// up; this source marks them as unconfirmed in the prompt.
    Pending,
}

/// Weights for hybrid memory search scoring components.
///
/// The hybrid score is *relevance-driven*: `vector` and `lexical` form the
/// relevance base that decides whether a memory is a candidate at all, while
/// `recency`, `salience`, `confidence`, `emotional_match`, `relationship`, and
/// `access_boost` form a multiplicative quality factor that only reorders
/// memories *within* the relevant set. Quality can therefore never lift an
/// irrelevant memory above a relevant one.
///
/// Product defaults are supplied by `mind.memory.hybrid_weights`
/// (`ene_mind::MindMemoryConfig`); the store only applies caller-provided
/// weights when scoring.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case", default)]
#[schemars(crate = "schemars")]
pub struct HybridSearchWeights {
    /// Relevance weight for vector cosine similarity.
    pub vector: f32,
    /// Relevance weight for lexical token overlap.
    pub lexical: f32,
    /// Quality weight for recency decay score.
    pub recency: f32,
    /// Quality weight for memory salience.
    pub salience: f32,
    /// Quality weight for memory confidence.
    pub confidence: f32,
    /// Quality weight for emotional/affect match.
    pub emotional_match: f32,
    /// Quality weight for relationship impact.
    pub relationship: f32,
    /// Quality weight for prior access boost.
    pub access_boost: f32,
}

impl Default for HybridSearchWeights {
    fn default() -> Self {
        Self {
            vector: 0.40,
            lexical: 0.15,
            recency: 0.10,
            salience: 0.15,
            confidence: 0.05,
            emotional_match: 0.05,
            relationship: 0.05,
            access_boost: 0.05,
        }
    }
}

/// A time range filter for memory queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeRange {
    /// Start of the time range (inclusive).
    pub start: Option<DateTime<Utc>>,
    /// End of the time range (inclusive).
    pub end: Option<DateTime<Utc>>,
}

/// Typed-memory search query.
///
/// Callers (mind) pre-compute `embedding` when vector search is desired.
/// `None` skips the vector gather path and scores lexical/recency/commitment
/// candidates only. The store never calls an embedder.
#[derive(Debug, Clone)]
pub struct Query<'a> {
    /// Natural-language query for lexical scoring.
    pub query_text: &'a str,
    /// Optional query embedding for vector similarity (`None` = lexical/recency only).
    pub embedding: Option<&'a [f32]>,
    /// Character scope.
    pub character_id: &'a str,
    /// Optional user scope filter.
    pub user_id: Option<&'a str>,
    /// Embedding model name for vector index lookup (ignored when `embedding` is `None`).
    pub model_name: &'a str,
    /// Maximum results to return.
    pub limit: usize,
    /// Minimum vector similarity for vector-sourced candidates.
    pub similarity_threshold: f32,
    /// Upper bound on candidates gathered before scoring.
    pub candidate_pool_size: usize,
    /// Optional query affect for emotional match scoring.
    pub query_affect: Option<AffectAnnotation>,
    /// Component weights for the hybrid formula.
    pub weights: HybridSearchWeights,
    /// Half-life in days for recency decay.
    pub decay_half_life_days: f64,
    /// Half-life in days for the access-boost recency decay.
    ///
    /// Independent of [`Self::decay_half_life_days`]: access history fades on
    /// this shorter timescale so old accesses stop boosting recall score well
    /// before the memory itself would fade. Defaults to
    /// `ene_rag::ACCESS_BOOST_HALF_LIFE_DAYS` (14.0) via mind config.
    pub access_boost_half_life_days: f64,
    /// Reference time for recency and expiry checks.
    pub now: DateTime<Utc>,
    /// Minimum hybrid total score required to return a result.
    pub min_score: f32,
    /// Boost applied when a candidate is surfaced via an active commitment.
    pub commitment_boost: f32,
    /// Filter by time range (for world state queries like "what was I doing yesterday?").
    pub time_range: Option<TimeRange>,
    /// Limit on pure-recent fallback candidates.
    pub recent_fallback_limit: usize,
    /// Memory kinds excluded from every gather path.
    ///
    /// Candidates of an excluded kind are dropped before scoring, so they
    /// never compete with normal memories in recall. The cognitive recall
    /// path uses this to keep [`MemoryKind::Reflection`] memories out of
    /// regular recall: reflections are a scoring signal (applied separately
    /// via the self-reflection pipeline), not context to inject into the LLM.
    /// An empty list excludes nothing.
    pub exclude_kinds: Vec<MemoryKind>,
}

/// Deprecated; prefer [`Query`].
pub type MemorySearchOptions<'a> = Query<'a>;

/// Filter options for the desktop/CLI memory journal browse list.
#[derive(Debug, Clone)]
pub struct MemoryJournalListOptions<'a> {
    /// Character scope.
    pub character_id: &'a str,
    /// When set, include rows scoped to this user or global (empty `user_id`).
    pub user_id: Option<&'a str>,
    /// Include archived memories.
    pub include_archived: bool,
    /// Include superseded memories.
    pub include_superseded: bool,
    /// Include user-deleted memories.
    pub include_user_deleted: bool,
    /// Optional kind filter.
    pub kind: Option<MemoryKind>,
    /// Maximum rows to return.
    pub limit: usize,
    /// Pagination offset.
    pub offset: usize,
}

/// Explainable score breakdown for a recalled memory.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MemoryScoreBreakdown {
    /// Raw vector cosine similarity.
    pub vector_similarity: f32,
    /// Lexical overlap score.
    pub lexical_score: f32,
    /// Recency decay score.
    pub recency_score: f32,
    /// Memory salience value.
    pub salience: f32,
    /// Memory confidence value used in the weighted score.
    pub confidence: f32,
    /// Affect match score.
    pub emotional_match: f32,
    /// Normalized relationship impact score.
    pub relationship: f32,
    /// Access-frequency boost.
    pub access_boost: f32,
    /// Combined query-relevance signal in `[0, 1]` — the weighted blend of
    /// vector similarity and lexical overlap that forms the score base.
    pub relevance: f32,
    /// Multiplicative quality factor `>= 1.0` built from the salience,
    /// confidence, recency, affect, relationship, and access signals.
    pub quality_factor: f32,
    /// Penalty for disputed status.
    pub contradiction_penalty: f32,
    /// Penalty for faded or expired memories.
    pub stale_penalty: f32,
    /// Boost for active commitment candidates.
    pub commitment_boost: f32,
    /// Self-reflection adjustment multiplier applied after scoring.
    ///
    /// `1.0` means no reflection adjustment. A value `> 1.0` boosts memories
    /// matching successful strategies; `< 1.0` penalizes memories matching
    /// strategies to avoid. Recorded so the explainable breakdown stays
    /// consistent: `total` is the pre-reflection score scaled by this factor,
    /// rather than a silent overwrite of `total`.
    pub reflection_multiplier: f32,
    /// Final hybrid total score.
    pub total: f32,
}

impl Default for MemoryScoreBreakdown {
    fn default() -> Self {
        Self {
            vector_similarity: 0.0,
            lexical_score: 0.0,
            recency_score: 0.0,
            salience: 0.0,
            confidence: 0.0,
            emotional_match: 0.0,
            relationship: 0.0,
            access_boost: 0.0,
            relevance: 0.0,
            quality_factor: 1.0,
            contradiction_penalty: 0.0,
            stale_penalty: 0.0,
            commitment_boost: 0.0,
            reflection_multiplier: 1.0,
            total: 0.0,
        }
    }
}

/// A typed memory with hybrid score breakdown and recall sources.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScoredMemory {
    /// The recalled memory item.
    pub item: MemoryItem,
    /// Explainable score components.
    pub breakdown: MemoryScoreBreakdown,
    /// Sources that contributed this candidate.
    pub sources: Vec<MemoryCandidateSource>,
}

/// A candidate gathered from one or more recall sources, before scoring.
///
/// Produced by [`MemoryPort::search`](crate::MemoryPort::search) and consumed
/// by the `ene-rag` scoring layer. Lives in `ene-core` so both the store
/// (gatherer) and the RAG crate (scorer) can name it without a cycle.
///
/// Carries `Serialize`/`Deserialize` so it can cross a process boundary in the
/// future (e.g. an out-of-process store). Note that each candidate embeds a full
/// [`MemoryItem`] — including its `content` string — so a large candidate set can
/// produce a sizeable serialized payload; any future IPC path should stay
/// size-aware (cap candidate counts, or send identifiers instead of full items).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GatheredCandidate {
    /// The recalled memory item.
    pub item: MemoryItem,
    /// Best vector cosine similarity across recall sources (0.0 when absent).
    pub vector_similarity: f32,
    /// Sources that contributed this candidate.
    pub sources: Vec<MemoryCandidateSource>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn memory_kind_serde_roundtrip() {
        let kinds = [
            MemoryKind::Episodic,
            MemoryKind::Semantic,
            MemoryKind::UserProfile,
            MemoryKind::Relationship,
            MemoryKind::Affective,
            MemoryKind::Commitment,
            MemoryKind::Preference,
            MemoryKind::Procedure,
            MemoryKind::WorldState,
            MemoryKind::Reflection,
        ];
        for kind in kinds {
            let json = serde_json::to_string(&kind).unwrap();
            let back: MemoryKind = serde_json::from_str(&json).unwrap();
            assert_eq!(kind, back, "roundtrip failed for {kind:?}");
        }
    }

    /// The per-kind policy table must cover every variant and encode
    /// exactly the documented first-class sets: 9 LLM-extractable kinds
    /// (`WorldState` is reserved, not extractable), 5 contradiction-checked kinds
    /// (the identity-like four plus Commitment), 4 diversification base-slot
    /// kinds, and every kind recall-eligible except Reflection.
    #[test]
    fn memory_kind_policy_table_is_exhaustive() {
        for kind in MemoryKind::ALL {
            let extractable = matches!(
                kind,
                MemoryKind::Episodic
                    | MemoryKind::Semantic
                    | MemoryKind::UserProfile
                    | MemoryKind::Relationship
                    | MemoryKind::Affective
                    | MemoryKind::Commitment
                    | MemoryKind::Preference
                    | MemoryKind::Procedure
                    | MemoryKind::Reflection
            );
            assert_eq!(
                kind.is_llm_extractable(),
                extractable,
                "is_llm_extractable mismatch for {kind:?}"
            );

            let contradiction_checked = matches!(
                kind,
                MemoryKind::Semantic
                    | MemoryKind::UserProfile
                    | MemoryKind::Preference
                    | MemoryKind::Relationship
                    | MemoryKind::Commitment
            );
            assert_eq!(
                kind.is_contradiction_kind(),
                contradiction_checked,
                "is_contradiction_kind mismatch for {kind:?}"
            );
            assert_eq!(
                kind.is_contradiction_kind(),
                kind.contradiction_key_match() == ContradictionKeyMatch::VectorTitle,
                "contradiction_key_match must agree with is_contradiction_kind for {kind:?}"
            );

            let base_slot = matches!(
                kind,
                MemoryKind::Semantic
                    | MemoryKind::Episodic
                    | MemoryKind::UserProfile
                    | MemoryKind::Commitment
            );
            assert_eq!(
                kind.has_diversification_base_slot(),
                base_slot,
                "has_diversification_base_slot mismatch for {kind:?}"
            );

            let recall_eligible = kind != MemoryKind::Reflection;
            assert_eq!(
                kind.is_recall_eligible(),
                recall_eligible,
                "is_recall_eligible mismatch for {kind:?}"
            );

            assert_eq!(
                kind.forgetting_policy(),
                ForgettingPolicy::Standard,
                "no per-kind forgetting differentiation exists yet; {kind:?} must be Standard"
            );
        }
    }

    /// `MemoryKind::ALL` is manually kept in sync with the variant list; a new
    /// variant omitted from it would silently escape every policy test that
    /// iterates `ALL`. The exhaustive `match` below makes that omission a
    /// compile error: adding a variant forces this test to be updated too.
    #[test]
    fn memory_kind_all_covers_every_variant() {
        let variants = match MemoryKind::Episodic {
            MemoryKind::Episodic
            | MemoryKind::Semantic
            | MemoryKind::UserProfile
            | MemoryKind::Relationship
            | MemoryKind::Affective
            | MemoryKind::Commitment
            | MemoryKind::Preference
            | MemoryKind::Procedure
            | MemoryKind::WorldState
            | MemoryKind::Reflection => [
                MemoryKind::Episodic,
                MemoryKind::Semantic,
                MemoryKind::UserProfile,
                MemoryKind::Relationship,
                MemoryKind::Affective,
                MemoryKind::Commitment,
                MemoryKind::Preference,
                MemoryKind::Procedure,
                MemoryKind::WorldState,
                MemoryKind::Reflection,
            ],
        };
        for kind in variants {
            assert!(
                MemoryKind::ALL.contains(&kind),
                "MemoryKind::ALL omits {kind:?}"
            );
        }
    }

    #[test]
    fn memory_status_serde_roundtrip() {
        let statuses = [
            MemoryStatus::Active,
            MemoryStatus::Faded,
            MemoryStatus::Archived,
            MemoryStatus::Disputed,
            MemoryStatus::Superseded,
            MemoryStatus::UserDeleted,
        ];
        for status in statuses {
            let json = serde_json::to_string(&status).unwrap();
            let back: MemoryStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(status, back, "roundtrip failed for {status:?}");
        }
    }

    #[test]
    fn memory_scope_serde_roundtrip() {
        let scopes = [
            MemoryScope::Character,
            MemoryScope::User,
            MemoryScope::Shared,
        ];
        for scope in scopes {
            let json = serde_json::to_string(&scope).unwrap();
            let back: MemoryScope = serde_json::from_str(&json).unwrap();
            assert_eq!(scope, back);
        }
    }

    #[test]
    fn memory_source_serde_roundtrip() {
        let sources = [
            MemorySource::Conversation,
            MemorySource::UserStated,
            MemorySource::LlmExtracted,
            MemorySource::Inferred,
            MemorySource::Imported,
            MemorySource::Ccv3,
        ];
        for source in sources {
            let json = serde_json::to_string(&source).unwrap();
            let back: MemorySource = serde_json::from_str(&json).unwrap();
            assert_eq!(source, back);
        }
    }

    #[test]
    fn memory_confidence_clamps() {
        assert!((MemoryConfidence::new(1.5).get() - 1.0).abs() < f32::EPSILON);
        assert!((MemoryConfidence::new(-0.3).get() - 0.0).abs() < f32::EPSILON);
        assert!((MemoryConfidence::new(0.73).get() - 0.73).abs() < f32::EPSILON);
        assert!((MemoryConfidence::new(f32::NAN).get() - 0.5).abs() < f32::EPSILON);
    }

    #[test]
    fn memory_salience_clamps() {
        assert!((MemorySalience::new(1.5).get() - 1.0).abs() < f32::EPSILON);
        assert!((MemorySalience::new(-0.3).get() - 0.0).abs() < f32::EPSILON);
        assert!((MemorySalience::new(f32::NAN).get() - 0.5).abs() < f32::EPSILON);
    }

    #[test]
    fn memory_item_serde_roundtrip() {
        let item = MemoryItem {
            id: Some(42),
            scope: MemoryScope::Character,
            character_id: "ene".into(),
            user_id: String::new(),
            kind: MemoryKind::Episodic,
            title: "Test memory".into(),
            content: "The user said hello".into(),
            source: MemorySource::Conversation,
            source_ref: Some("sess-1/turn-3".into()),
            confidence: MemoryConfidence::new(0.9),
            salience: MemorySalience::new(0.7),
            affect: AffectAnnotation {
                valence: 0.3,
                arousal: -0.1,
            },
            relationship_impact: 0.2,
            access_count: 5,
            last_accessed_at: Some(chrono::Utc::now()),
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
            valid_from: None,
            valid_until: None,
            status: MemoryStatus::Active,
            supersedes_id: None,
            pinned: false,
            faded_at: None,
            commitment_id: None,
        };
        let json = serde_json::to_string(&item).unwrap();
        let back: MemoryItem = serde_json::from_str(&json).unwrap();
        assert_eq!(item.id, back.id);
        assert_eq!(item.scope, back.scope);
        assert_eq!(item.kind, back.kind);
        assert_eq!(item.title, back.title);
        assert_eq!(item.content, back.content);
        assert_eq!(item.source, back.source);
        assert_eq!(item.status, back.status);
        assert!((item.confidence.get() - back.confidence.get()).abs() < f32::EPSILON);
        assert!((item.salience.get() - back.salience.get()).abs() < f32::EPSILON);
    }

    #[test]
    fn new_memory_item_serde_roundtrip() {
        let new_item = NewMemoryItem {
            scope: MemoryScope::User,
            character_id: "ene".into(),
            user_id: "user-1".into(),
            kind: MemoryKind::Preference,
            title: "Likes cats".into(),
            content: "The user mentioned they like cats".into(),
            source: MemorySource::LlmExtracted,
            source_ref: None,
            confidence: MemoryConfidence::new(0.8),
            salience: MemorySalience::new(0.6),
            affect: AffectAnnotation::default(),
            relationship_impact: 0.0,
            valid_from: None,
            valid_until: None,
            status: MemoryStatus::Active,
            supersedes_id: None,
            pinned: false,
            created_at: None,
            commitment_id: None,
        };
        let json = serde_json::to_string(&new_item).unwrap();
        let back: NewMemoryItem = serde_json::from_str(&json).unwrap();
        assert_eq!(new_item.kind, back.kind);
        assert_eq!(new_item.title, back.title);
    }
}
