[package]
name = "ene-credential"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ene-primitive = { path = "../ene-primitive" }
hmac.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true

[lints]
workspace = true
