[package]
name = "ene-preservation"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
test-support = []

[dependencies]
ene-primitive = { path = "../ene-primitive" }
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
