[package]
name = "ene-tools-utility"
version = "0.1.0"
edition = "2024"

[dependencies]
ene-tool-proto = { path = "../../ene-tool-proto" }
ene-tools-common = { path = "../common" }
chrono = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
dashmap = "6"

[[bin]]
name = "ene-tools-utility"
path = "src/main.rs"
