[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Zshare-generics=y",
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--icf=all",
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-arg=-static",
]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
