//! Per-tool DB IPC server using SeaORM.
//!
//! Listens on a Unix socket, accepts tool connections, and dispatches
//! [`DbRequest`] messages against the shared `memory.db`.
//!
//! ## Security model
//!
//! - Each tool declares its schema (tables + columns) via `DeclareSchema`.
//! - The server records the declaration in `__tool_schemas` and enforces that
//!   all subsequent requests only reference tables/columns in the declaration.
//! - Table names must start with the tool's prefix (e.g. `fs_`, `utility_`).
//! - DDL (CREATE/ALTER/DROP) is **not** exposed to tools.
//! - `sqlite_master` and other internal tables are blocked.
//!
//! ## Schema evolution
//!
//! On every `DeclareSchema` the server hashes the declaration (BLAKE3) and
//! compares it against the `fingerprint` stored in `__tool_schemas`:
//!
//! - **Unchanged** — the stored row is left untouched (no needless rewrite) and
//!   the existing tables are reused as-is.
//! - **Additive change** (new table, or a new column on an existing table) —
//!   the new column is applied with `ALTER TABLE ... ADD COLUMN`, the stored
//!   declaration is refreshed, and the tool proceeds. `SQLite` fills existing
//!   rows with the column's `DEFAULT` (or `NULL`).
//! - **Conflicting change** (a column type change, a previously declared
//!   table or column dropped from the declaration, or a new column that
//!   carries a `PRIMARY KEY`/`UNIQUE`/`AUTOINCREMENT` constraint) — rejected
//!   with [`DbServerError::SchemaConflict`]. `SQLite` cannot alter or drop
//!   columns in place, nor add a constrained column, so the host refuses to
//!   let the validation layer and the actual tables silently diverge; the
//!   plugin author must reconcile the difference.

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::sync::Arc;

use crate::entities::tool_schemas;
use ene_plugin_db::{
    DbColumn, DbErrorCode, DbFilter, DbOrderBy, DbRequest, DbResponse, DbSchema, DbTable, DbType,
    DbValue, Row,
};
use sea_orm::sea_query::{Alias, Condition, Expr, Query, SqliteQueryBuilder};
use sea_orm::{
    ConnectionTrait, DatabaseBackend, DatabaseConnection, EntityTrait, ExprTrait, Statement,
};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tracing::{debug, error, info, warn};

/// Errors from the DB IPC server.
#[derive(Debug, thiserror::Error)]
pub enum DbServerError {
    /// IO error.
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    /// JSON serialization/deserialization error.
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),
    /// `SeaORM` database error.
    #[error("Database error: {0}")]
    Db(#[from] sea_orm::DbErr),
    /// The tool does not have permission to access the resource.
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    /// The specified table is unknown or not declared.
    #[error("Unknown table: {0}")]
    UnknownTable(String),
    /// The specified column is unknown.
    #[error("Unknown column: {table}.{column}")]
    UnknownColumn {
        /// Table name.
        table: String,
        /// Column name.
        column: String,
    },
    /// The declared schema conflicts with the one already stored for this
    /// prefix in a way that cannot be applied automatically (e.g. a column
    /// type change or a removed table). The plugin must reconcile the
    /// difference explicitly rather than having the host silently diverge.
    #[error("Schema conflict: {0}")]
    SchemaConflict(String),
    /// An internal server error.
    #[error("Internal error: {0}")]
    Internal(String),
}

impl DbServerError {
    fn to_error_response(&self) -> DbResponse {
        let (code, message) = match self {
            Self::PermissionDenied(msg) => (DbErrorCode::PermissionDenied, msg.clone()),
            Self::UnknownTable(msg) => (DbErrorCode::UnknownTable, msg.clone()),
            Self::UnknownColumn { table, column } => (
                DbErrorCode::UnknownColumn,
                format!("Unknown column: {table}.{column}"),
            ),
            Self::SchemaConflict(msg) => (DbErrorCode::SchemaConflict, msg.clone()),
            Self::Io(e) => (DbErrorCode::Internal, e.to_string()),
            Self::Json(e) => (DbErrorCode::Internal, e.to_string()),
            Self::Db(e) => (DbErrorCode::Internal, e.to_string()),
            Self::Internal(msg) => (DbErrorCode::Internal, msg.clone()),
        };
        DbResponse::Error { code, message }
    }
}

/// Per-tool DB IPC server.
pub struct DbIpcServer {
    db: DatabaseConnection,
    socket_path: PathBuf,
    tool_name: String,
    prefix: String,
    /// Pre-shared auth token required on the very first request of
    /// every connection. Generated by the parent and passed to the
    /// tool binary via the `ENE_DB_AUTH_TOKEN` env var.
    auth_token: String,
}

impl DbIpcServer {
    /// Creates a new server for the given tool.
    ///
    /// `db` must be a sea-orm database connection that is already
    /// open, has had its PRAGMAs applied, and has had migrations run.
    /// The caller is responsible for providing a connection from
    /// the same pool that `MemoryStore` uses.
    pub const fn new(
        db: DatabaseConnection,
        socket_path: PathBuf,
        tool_name: String,
        prefix: String,
        auth_token: String,
    ) -> Self {
        Self {
            db,
            socket_path,
            tool_name,
            prefix,
            auth_token,
        }
    }

    /// Runs the server, listening for connections and handling requests.
    pub async fn run(self) -> Result<(), DbServerError> {
        // On Unix, remove any stale socket file from a previous run
        // before binding. Named pipes are kernel objects, not
        // filesystem objects, so this step is a no-op on Windows.
        #[cfg(unix)]
        if self.socket_path.exists() {
            tokio::fs::remove_file(&self.socket_path).await?;
        }

        let mut listener = ene_plugin_proto::transport::IpcListener::bind(&self.socket_path)?;

        // Restrict the unix socket to the owning user. Without this
        // chmod the socket in /tmp is world-connectable, allowing any
        // local process to connect and issue DeclareSchema on the tool's
        // behalf (combined with the SQL-injection vector fixed in
        // #23 this is a privilege escalation). Named pipes use a
        // per-handle ACL instead, which the kernel sets when we bind.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o600);
            if let Err(e) = std::fs::set_permissions(&self.socket_path, perms) {
                return Err(DbServerError::Internal(format!(
                    "failed to chmod DB socket to 0o600: {e}"
                )));
            }
        }

        info!(
            tool = %self.tool_name,
            socket = %self.socket_path.display(),
            "DB IPC server listening"
        );

        #[expect(
            clippy::infinite_loop,
            reason = "DB IPC accept loop runs until the server task is cancelled"
        )]
        loop {
            // Continue the accept loop on transient accept
            // errors (EMFILE, ENFILE, EINTR, ...). A
            // permanent kill of the DB server on a single
            // resource-exhaustion event would leave the
            // tool offline until the next reconfigure.
            // The errors that *do* terminate the server
            // (broken listener, socket removed, etc.) are
            // surfaced via the original `?` on the
            // `accept()` call only after we have logged
            // and backed off, so a single transient
            // failure does not silently break the tool.
            let stream = match listener.accept().await {
                Ok(stream) => stream,
                Err(e) => {
                    error!(
                        tool = %self.tool_name,
                        error = %e,
                        "DB IPC accept failed; backing off and continuing"
                    );
                    // Exponential backoff capped at 5s.
                    // The previous behavior was `?`-propagate,
                    // which killed the server task on a
                    // single accept failure.
                    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                    continue;
                }
            };
            debug!(tool = %self.tool_name, "Accepted DB IPC connection");

            let db = self.db.clone();
            let tool_name = self.tool_name.clone();
            let prefix = self.prefix.clone();
            let auth_token = self.auth_token.clone();

            tokio::spawn(async move {
                if let Err(e) =
                    Self::handle_connection(stream, db, tool_name, prefix, auth_token).await
                {
                    error!(error = %e, "DB IPC connection error");
                }
            });
        }
    }

    async fn handle_connection(
        stream: ene_plugin_proto::transport::IpcStream,
        db: DatabaseConnection,
        tool_name: String,
        prefix: String,
        auth_token: String,
    ) -> Result<(), DbServerError> {
        let mut stream = stream;

        // Track the rowid of the most recent Insert so that
        // a subsequent `LastInsertRowId` request can return
        // the correct value. SQLite's `last_insert_rowid()`
        // is per-connection; with SeaORM's pool, the
        // connection serving a query may not be the one
        // that performed the prior insert, so a raw
        // `SELECT last_insert_rowid()` is racy. Tracking
        // it here (one cell per logical `handle_connection`)
        // matches the tool's own view: a tool client
        // always pairs Insert and LastInsertRowId on the
        // same connection.
        let last_rowid: Arc<std::sync::Mutex<Option<i64>>> = Arc::new(std::sync::Mutex::new(None));

        let mut declared_tables: HashMap<String, DbTable> = HashMap::new();
        let mut declared_columns: HashMap<String, HashSet<String>> = HashMap::new();

        let mut authenticated = false;

        loop {
            let mut len_buf = [0u8; 4];
            match stream.read_exact(&mut len_buf).await {
                Ok(_) => {}
                Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => {
                    debug!(tool = %tool_name, "DB IPC connection closed");
                    break;
                }
                Err(e) => return Err(DbServerError::Io(e)),
            }
            let Ok(msg_len) = usize::try_from(u32::from_le_bytes(len_buf)) else {
                return Err(DbServerError::Internal(
                    "message length overflow on this platform".to_string(),
                ));
            };
            if msg_len > 64 * 1024 * 1024 {
                return Err(DbServerError::Internal(format!(
                    "message too large: {msg_len}"
                )));
            }

            let mut msg_buf = vec![0u8; msg_len];
            stream.read_exact(&mut msg_buf).await?;

            let request: DbRequest = match serde_json::from_slice(&msg_buf) {
                Ok(req) => req,
                Err(e) => {
                    warn!(tool = %tool_name, error = %e, "Invalid JSON in DB request");
                    let response = DbResponse::Error {
                        code: DbErrorCode::Internal,
                        message: format!("Invalid JSON: {e}"),
                    };
                    Self::send_response(&mut stream, &response).await?;
                    continue;
                }
            };

            // Enforce handshake: the very first request of any new
            // connection must carry the pre-shared auth token. Any
            // other request is rejected and the connection is closed.
            if !authenticated {
                let response = match &request {
                    DbRequest::Handshake { token } if token == &auth_token => {
                        authenticated = true;
                        DbResponse::HandshakeAck
                    }
                    DbRequest::Handshake { .. } => {
                        warn!(
                            tool = %tool_name,
                            "DB IPC handshake failed: bad token"
                        );
                        DbResponse::Error {
                            code: DbErrorCode::PermissionDenied,
                            message: "Invalid auth token".to_string(),
                        }
                    }
                    _ => {
                        warn!(
                            tool = %tool_name,
                            "DB IPC request before handshake; closing"
                        );
                        DbResponse::Error {
                            code: DbErrorCode::PermissionDenied,
                            message: "Handshake required".to_string(),
                        }
                    }
                };
                Self::send_response(&mut stream, &response).await?;
                if !authenticated {
                    break;
                }
                continue;
            }

            // Match the actual `Shutdown` request rather
            // than the response. The previous form closed
            // the connection on any `DbResponse::Ack`, which
            // is fragile: if any other request ever returns
            // `Ack` (or a future response is reused), the
            // connection would terminate spuriously.
            let was_shutdown = matches!(request, DbRequest::Shutdown);

            let response = Self::handle_request(
                &db,
                &tool_name,
                &prefix,
                &mut declared_tables,
                &mut declared_columns,
                &last_rowid,
                request,
            )
            .await;

            Self::send_response(&mut stream, &response).await?;

            if was_shutdown {
                debug!(tool = %tool_name, "Received shutdown request");
                break;
            }
        }

        Ok(())
    }

    async fn send_response(
        stream: &mut ene_plugin_proto::transport::IpcStream,
        response: &DbResponse,
    ) -> Result<(), DbServerError> {
        let json = serde_json::to_vec(response)?;
        let len = json.len() as u32;
        stream.write_all(&len.to_le_bytes()).await?;
        stream.write_all(&json).await?;
        stream.flush().await?;
        Ok(())
    }

    async fn handle_request(
        db: &DatabaseConnection,
        tool_name: &str,
        prefix: &str,
        declared_tables: &mut HashMap<String, DbTable>,
        declared_columns: &mut HashMap<String, HashSet<String>>,
        last_rowid: &Arc<std::sync::Mutex<Option<i64>>>,
        request: DbRequest,
    ) -> DbResponse {
        match request {
            DbRequest::DeclareSchema(schema) => Self::handle_declare_schema(
                db,
                tool_name,
                prefix,
                declared_tables,
                declared_columns,
                schema,
            )
            .await
            .unwrap_or_else(|e| e.to_error_response()),
            DbRequest::Insert { table, row } => {
                let res = Self::validate_table_access(declared_tables, &table)
                    .and_then(|()| Self::validate_row_columns(declared_columns, &table, &row));
                match res {
                    Ok(()) => match Self::handle_insert(db, &table, row).await {
                        Ok(id) => {
                            // Record the rowid for the
                            // connection-scoped
                            // `LastInsertRowId` lookup.
                            if let Ok(mut guard) = last_rowid.lock() {
                                *guard = Some(id);
                            }
                            DbResponse::Insert { rowid: id }
                        }
                        Err(e) => e.to_error_response(),
                    },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::Upsert {
                table,
                row,
                conflict_columns,
            } => {
                let res = Self::validate_table_access(declared_tables, &table)
                    .and_then(|()| Self::validate_row_columns(declared_columns, &table, &row));
                match res {
                    Ok(()) => match Self::handle_upsert(db, &table, row, conflict_columns).await {
                        Ok(rowid) => DbResponse::Upsert { rowid },
                        Err(e) => e.to_error_response(),
                    },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::Select {
                table,
                columns,
                filter,
                order_by,
                limit,
            } => {
                match Self::handle_select(
                    db,
                    declared_tables,
                    declared_columns,
                    &table,
                    columns,
                    filter,
                    order_by,
                    limit,
                )
                .await
                {
                    Ok(rows) => DbResponse::Select { rows },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::Update { table, set, filter } => {
                let res = Self::validate_table_access(declared_tables, &table)
                    .and_then(|()| Self::validate_row_columns(declared_columns, &table, &set))
                    .and_then(|()| {
                        Self::validate_filter_columns(declared_columns, &table, &filter)
                    });
                match res {
                    Ok(()) => match Self::handle_update(db, &table, set, filter).await {
                        Ok(affected) => DbResponse::Update { affected },
                        Err(e) => e.to_error_response(),
                    },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::Delete { table, filter } => {
                let res = Self::validate_table_access(declared_tables, &table).and_then(|()| {
                    Self::validate_filter_columns(declared_columns, &table, &filter)
                });
                match res {
                    Ok(()) => match Self::handle_delete(db, &table, filter).await {
                        Ok(affected) => DbResponse::Delete { affected },
                        Err(e) => e.to_error_response(),
                    },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::Count { table, filter } => {
                let res = Self::validate_table_access(declared_tables, &table).and_then(|()| {
                    Self::validate_filter_columns(declared_columns, &table, &filter)
                });
                match res {
                    Ok(()) => match Self::handle_count(db, &table, filter).await {
                        Ok(count) => DbResponse::Count { count },
                        Err(e) => e.to_error_response(),
                    },
                    Err(e) => e.to_error_response(),
                }
            }
            DbRequest::LastInsertRowId => {
                // Return the rowid of the most recent
                // Insert on this logical connection. SQLite's
                // `last_insert_rowid()` is per-connection, so
                // a raw `SELECT last_insert_rowid()` against
                // a SeaORM pool can return a stale or
                // different value than the prior insert.
                let rowid = last_rowid.lock().ok().and_then(|g| *g).unwrap_or(0);
                DbResponse::LastInsertRowId { rowid }
            }
            DbRequest::Ping => DbResponse::Pong,
            DbRequest::Shutdown => DbResponse::Ack,
            // The handshake is intercepted in `handle_connection`
            // before reaching this dispatch; reaching it here means
            // a second handshake was sent, which we reject.
            DbRequest::Handshake { .. } => DbResponse::Error {
                code: DbErrorCode::PermissionDenied,
                message: "Handshake already completed".to_string(),
            },
        }
    }

    fn validate_table_access(
        declared_tables: &HashMap<String, DbTable>,
        table: &str,
    ) -> Result<(), DbServerError> {
        if table.starts_with("sqlite_") || table == "__tool_schemas" {
            return Err(DbServerError::PermissionDenied(format!(
                "Access to internal table '{table}' is not allowed"
            )));
        }

        if !declared_tables.contains_key(table) {
            return Err(DbServerError::UnknownTable(table.to_string()));
        }

        Ok(())
    }

    fn validate_row_columns(
        declared_columns: &HashMap<String, HashSet<String>>,
        table: &str,
        row: &Row,
    ) -> Result<(), DbServerError> {
        let table_columns = declared_columns
            .get(table)
            .ok_or_else(|| DbServerError::UnknownTable(table.to_string()))?;

        for col in row.keys() {
            if !table_columns.contains(col) {
                return Err(DbServerError::UnknownColumn {
                    table: table.to_string(),
                    column: col.clone(),
                });
            }
        }

        Ok(())
    }

    fn validate_select_columns(
        declared_columns: &HashMap<String, HashSet<String>>,
        table: &str,
        columns: &[String],
    ) -> Result<(), DbServerError> {
        if columns.is_empty() {
            return Ok(());
        }

        let table_columns = declared_columns
            .get(table)
            .ok_or_else(|| DbServerError::UnknownTable(table.to_string()))?;

        for col in columns {
            if !table_columns.contains(col) {
                return Err(DbServerError::UnknownColumn {
                    table: table.to_string(),
                    column: col.clone(),
                });
            }
        }

        Ok(())
    }

    fn validate_filter_columns(
        declared_columns: &HashMap<String, HashSet<String>>,
        table: &str,
        filter: &DbFilter,
    ) -> Result<(), DbServerError> {
        let table_columns = declared_columns
            .get(table)
            .ok_or_else(|| DbServerError::UnknownTable(table.to_string()))?;

        for col in filter.columns_referenced() {
            if !table_columns.contains(col) {
                return Err(DbServerError::UnknownColumn {
                    table: table.to_string(),
                    column: col.to_string(),
                });
            }
        }

        Ok(())
    }

    fn validate_order_by_columns(
        declared_columns: &HashMap<String, HashSet<String>>,
        table: &str,
        order_by: &[DbOrderBy],
    ) -> Result<(), DbServerError> {
        let table_columns = declared_columns
            .get(table)
            .ok_or_else(|| DbServerError::UnknownTable(table.to_string()))?;

        for order in order_by {
            if !table_columns.contains(&order.column) {
                return Err(DbServerError::UnknownColumn {
                    table: table.to_string(),
                    column: order.column.clone(),
                });
            }
        }

        Ok(())
    }

    async fn handle_declare_schema(
        db: &DatabaseConnection,
        tool_name: &str,
        prefix: &str,
        declared_tables: &mut HashMap<String, DbTable>,
        declared_columns: &mut HashMap<String, HashSet<String>>,
        schema: DbSchema,
    ) -> Result<DbResponse, DbServerError> {
        if schema.prefix != prefix {
            return Err(DbServerError::PermissionDenied(format!(
                "Schema prefix '{}' does not match tool prefix '{}'",
                schema.prefix, prefix
            )));
        }

        for table in &schema.tables {
            if !table.name.starts_with(prefix) {
                return Err(DbServerError::PermissionDenied(format!(
                    "Table '{}' does not start with prefix '{}'",
                    table.name, prefix
                )));
            }
            Self::validate_identifier(&table.name)?;
            for col in &table.columns {
                Self::validate_identifier(&col.name)?;
            }
        }

        let known_table_names: HashSet<&str> =
            schema.tables.iter().map(|t| t.name.as_str()).collect();
        for index in &schema.indexes {
            Self::validate_identifier(&index.name)?;
            Self::validate_identifier(&index.table)?;
            if !index.table.starts_with(prefix) {
                return Err(DbServerError::PermissionDenied(format!(
                    "Index '{}' references table '{}' outside prefix '{}'",
                    index.name, index.table, prefix
                )));
            }
            if !known_table_names.contains(index.table.as_str()) {
                return Err(DbServerError::UnknownTable(format!(
                    "Index '{}' references undeclared table '{}'",
                    index.name, index.table
                )));
            }
            for col in &index.columns {
                Self::validate_identifier(col)?;
            }
        }

        let schema_json = serde_json::to_string(&schema)
            .map_err(|e| DbServerError::Internal(format!("Failed to serialize schema: {e}")))?;

        let fingerprint = blake3::hash(schema_json.as_bytes()).to_hex().to_string();

        // Compare against the previously stored declaration, if any. The
        // fingerprint was historically written but never read (#423); it now
        // gates whether the stored row is rewritten and whether the physical
        // tables need additive migration.
        let stored = tool_schemas::Entity::find_by_id(prefix)
            .one(db)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        let mut created_indexes = Vec::new();

        match &stored {
            // Unchanged schema: reuse the existing tables verbatim and leave
            // the stored row untouched so an unchanged declaration does not
            // rewrite it needlessly.
            Some(row) if row.fingerprint == fingerprint => {
                debug!(
                    tool = %tool_name,
                    prefix = %prefix,
                    "Schema unchanged; reusing stored declaration"
                );
            }
            // First declaration, or the schema changed: reconcile the
            // physical tables with the new declaration, then refresh the
            // stored row.
            _ => {
                let previous = stored
                    .as_ref()
                    .map(|row| {
                        serde_json::from_str::<DbSchema>(&row.schema_json).map_err(|e| {
                            DbServerError::Internal(format!(
                                "stored schema for prefix '{prefix}' is corrupt: {e}"
                            ))
                        })
                    })
                    .transpose()?;

                Self::apply_schema_change(db, tool_name, prefix, previous.as_ref(), &schema)
                    .await?;

                let active_model = tool_schemas::ActiveModel {
                    prefix: sea_orm::ActiveValue::Set(prefix.to_string()),
                    schema_json: sea_orm::ActiveValue::Set(schema_json.clone()),
                    fingerprint: sea_orm::ActiveValue::Set(fingerprint.clone()),
                    created_at: sea_orm::ActiveValue::Set(chrono::Utc::now()),
                };

                tool_schemas::Entity::insert(active_model)
                    .on_conflict(
                        sea_orm::sea_query::OnConflict::column(tool_schemas::Column::Prefix)
                            .update_columns([
                                tool_schemas::Column::SchemaJson,
                                tool_schemas::Column::Fingerprint,
                                tool_schemas::Column::CreatedAt,
                            ])
                            .to_owned(),
                    )
                    .exec(db)
                    .await
                    .map_err(|e| DbServerError::Internal(e.to_string()))?;
            }
        }

        // Idempotent regardless of the branch above: `CREATE TABLE IF NOT
        // EXISTS` / `CREATE INDEX IF NOT EXISTS` are no-ops on existing
        // objects and create any that are missing.
        for table in &schema.tables {
            let create_sql = Self::build_create_table_sql(table);
            db.execute_raw(Statement::from_string(DatabaseBackend::Sqlite, create_sql))
                .await
                .map_err(|e| DbServerError::Internal(e.to_string()))?;

            for index in &schema.indexes {
                if index.table == table.name {
                    let create_index_sql = Self::build_create_index_sql(index);
                    db.execute_raw(Statement::from_string(
                        DatabaseBackend::Sqlite,
                        create_index_sql,
                    ))
                    .await
                    .map_err(|e| DbServerError::Internal(e.to_string()))?;
                    created_indexes.push(index.name.clone());
                }
            }
        }

        for table in &schema.tables {
            let columns: HashSet<String> = table.columns.iter().map(|c| c.name.clone()).collect();
            declared_columns.insert(table.name.clone(), columns);
            declared_tables.insert(table.name.clone(), table.clone());
        }

        info!(
            tool = %tool_name,
            prefix = %prefix,
            tables = schema.tables.len(),
            "Schema declared"
        );

        Ok(DbResponse::SchemaAccepted {
            tables: schema.tables.iter().map(|t| t.name.clone()).collect(),
            indexes: created_indexes,
        })
    }

    /// Reconciles the physical tables with a changed schema declaration.
    ///
    /// `previous` is the last stored declaration for this prefix, if any.
    /// Additive changes (new tables, new columns) are applied in place;
    /// changes `SQLite` cannot perform in place (a column type change, or a
    /// previously declared table removed from the declaration) are rejected
    /// with [`DbServerError::SchemaConflict`] so the validation layer and the
    /// actual tables never silently diverge.
    async fn apply_schema_change(
        db: &DatabaseConnection,
        tool_name: &str,
        prefix: &str,
        previous: Option<&DbSchema>,
        new: &DbSchema,
    ) -> Result<(), DbServerError> {
        let Some(previous) = previous else {
            // First declaration for this prefix: nothing to migrate. The
            // caller's `CREATE TABLE IF NOT EXISTS` pass creates the tables.
            return Ok(());
        };

        let diff = Self::diff_schemas(previous, new)?;

        if diff.added_columns.is_empty() && diff.added_tables.is_empty() {
            // The fingerprint differs but there is nothing additive to apply
            // (e.g. only an index changed). Indexes are reconciled by the
            // caller's `CREATE INDEX IF NOT EXISTS` pass.
            return Ok(());
        }

        for (table, column) in &diff.added_columns {
            let alter_sql = Self::build_alter_add_column_sql(table, column);
            db.execute_raw(Statement::from_string(DatabaseBackend::Sqlite, alter_sql))
                .await
                .map_err(|e| {
                    DbServerError::Internal(format!(
                        "failed to add column '{}.{}': {e}",
                        table.name, column.name
                    ))
                })?;
            info!(
                tool = %tool_name,
                prefix = %prefix,
                table = %table.name,
                column = %column.name,
                "Applied additive schema change (ALTER TABLE ADD COLUMN)"
            );
        }

        for table in &diff.added_tables {
            info!(
                tool = %tool_name,
                prefix = %prefix,
                table = %table.name,
                "New table declared; will be created"
            );
        }

        Ok(())
    }

    /// Computes the additive diff between a stored schema and a new one.
    ///
    /// Returns the tables and columns that were added. Returns
    /// [`DbServerError::SchemaConflict`] if the new declaration removes a
    /// previously declared table or changes an existing column's type, since
    /// neither can be applied to the live `SQLite` tables in place.
    fn diff_schemas(previous: &DbSchema, new: &DbSchema) -> Result<SchemaDiff, DbServerError> {
        let previous_tables: HashMap<&str, &DbTable> = previous
            .tables
            .iter()
            .map(|t| (t.name.as_str(), t))
            .collect();

        let mut diff = SchemaDiff::default();

        for table in &new.tables {
            let Some(old_table) = previous_tables.get(table.name.as_str()) else {
                diff.added_tables.push(table.clone());
                continue;
            };

            let old_columns: HashMap<&str, &DbColumn> = old_table
                .columns
                .iter()
                .map(|c| (c.name.as_str(), c))
                .collect();

            for column in &table.columns {
                match old_columns.get(column.name.as_str()) {
                    // Brand-new column. `ALTER TABLE ADD COLUMN` can only add
                    // a plain column: SQLite forbids adding one that carries a
                    // PRIMARY KEY, UNIQUE, or AUTOINCREMENT constraint, so such
                    // an addition is rejected explicitly rather than failing
                    // with a cryptic error at execution time.
                    None => {
                        if column.primary_key || column.auto_increment || column.unique {
                            return Err(DbServerError::SchemaConflict(format!(
                                "column '{}.{}' was added with a PRIMARY KEY/UNIQUE/AUTOINCREMENT constraint; SQLite cannot add such a column via ALTER TABLE, so the plugin must reconcile this change explicitly",
                                table.name, column.name
                            )));
                        }
                        diff.added_columns.push((table.clone(), column.clone()));
                    }
                    // Existing column with a changed type: SQLite cannot
                    // change a column type in place, so refuse rather than
                    // let validation and storage diverge.
                    Some(old_column) if old_column.ty != column.ty => {
                        return Err(DbServerError::SchemaConflict(format!(
                            "column '{}.{}' changed type from {:?} to {:?}; SQLite cannot alter column types in place, so the plugin must reconcile this change explicitly",
                            table.name, column.name, old_column.ty, column.ty
                        )));
                    }
                    Some(_) => {}
                }
            }

            // A column present in the stored table but absent from the new
            // declaration would leave the physical column behind while
            // validation stops referencing it. Refuse so the author handles
            // the removal explicitly.
            let new_column_names: HashSet<&str> =
                table.columns.iter().map(|c| c.name.as_str()).collect();
            for old_column in &old_table.columns {
                if !new_column_names.contains(old_column.name.as_str()) {
                    return Err(DbServerError::SchemaConflict(format!(
                        "column '{}.{}' was removed from the schema declaration; SQLite cannot drop columns in place, so the plugin must reconcile this change explicitly",
                        table.name, old_column.name
                    )));
                }
            }
        }

        // A table present in the stored declaration but absent from the new
        // one would leave the physical table behind while validation stops
        // referencing it. Refuse so the author handles the removal explicitly.
        let new_table_names: HashSet<&str> = new.tables.iter().map(|t| t.name.as_str()).collect();
        for old_table in &previous.tables {
            if !new_table_names.contains(old_table.name.as_str()) {
                return Err(DbServerError::SchemaConflict(format!(
                    "table '{}' was removed from the schema declaration; SQLite cannot drop tables in place, so the plugin must reconcile this change explicitly",
                    old_table.name
                )));
            }
        }

        Ok(diff)
    }

    /// Builds an `ALTER TABLE ... ADD COLUMN` statement for an added column.
    ///
    /// `SQLite` forbids adding a column that carries a `PRIMARY KEY`,
    /// `UNIQUE`, or `AUTOINCREMENT` constraint, so none are emitted here;
    /// [`Self::diff_schemas`] rejects such additions before this is reached.
    /// `NOT NULL` is only emitted alongside a `DEFAULT`, matching `SQLite`'s
    /// `ADD COLUMN` requirement that a non-nullable added column have a
    /// default to populate existing rows.
    fn build_alter_add_column_sql(table: &DbTable, column: &DbColumn) -> String {
        let mut sql = format!("ALTER TABLE {} ADD COLUMN {} ", table.name, column.name);

        sql.push_str(match column.ty {
            DbType::Integer | DbType::Boolean => "INTEGER",
            DbType::Real => "REAL",
            DbType::Text => "TEXT",
            DbType::Blob => "BLOB",
        });

        // SQLite requires a DEFAULT for a NOT NULL column added via ALTER.
        if !column.nullable && column.default.is_some() {
            sql.push_str(" NOT NULL");
        }

        if let Some(default) = &column.default {
            sql.push_str(" DEFAULT ");
            sql.push_str(&Self::db_value_to_sql(default));
        }

        sql
    }

    /// Validates a SQL identifier (table, column, or index name).
    ///
    /// Rejects empty strings, names longer than 64 characters, and any
    /// character outside `[A-Za-z0-9_]` with the first character in
    /// `[A-Za-z_]`. This prevents SQL injection through identifier
    /// interpolation in DDL construction.
    #[expect(
        clippy::indexing_slicing,
        reason = "indexes into validated identifier bytes after length check"
    )]
    fn validate_identifier(name: &str) -> Result<(), DbServerError> {
        if name.is_empty() {
            return Err(DbServerError::PermissionDenied(
                "Identifier must not be empty".to_string(),
            ));
        }
        if name.len() > 64 {
            return Err(DbServerError::PermissionDenied(format!(
                "Identifier '{name}' exceeds 64-character limit"
            )));
        }
        let bytes = name.as_bytes();
        if !matches!(bytes[0], b'A'..=b'Z' | b'a'..=b'z' | b'_') {
            return Err(DbServerError::PermissionDenied(format!(
                "Identifier '{name}' must start with a letter or underscore"
            )));
        }
        for &b in &bytes[1..] {
            if !matches!(b, b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'_') {
                return Err(DbServerError::PermissionDenied(format!(
                    "Identifier '{name}' contains invalid character"
                )));
            }
        }
        Ok(())
    }

    fn build_create_table_sql(table: &DbTable) -> String {
        let mut sql = format!("CREATE TABLE IF NOT EXISTS {} (", table.name);

        let mut first = true;
        for col in &table.columns {
            if !first {
                sql.push_str(", ");
            }
            first = false;

            sql.push_str(&col.name);
            sql.push(' ');
            sql.push_str(match col.ty {
                ene_plugin_db::DbType::Integer | ene_plugin_db::DbType::Boolean => "INTEGER",
                ene_plugin_db::DbType::Real => "REAL",
                ene_plugin_db::DbType::Text => "TEXT",
                ene_plugin_db::DbType::Blob => "BLOB",
            });

            if !col.nullable {
                sql.push_str(" NOT NULL");
            }

            if col.primary_key {
                sql.push_str(" PRIMARY KEY");
            }

            if col.auto_increment {
                sql.push_str(" AUTOINCREMENT");
            }

            if col.unique {
                sql.push_str(" UNIQUE");
            }

            if let Some(default) = &col.default {
                sql.push_str(" DEFAULT ");
                sql.push_str(&Self::db_value_to_sql(default));
            }
        }

        sql.push(')');
        sql
    }

    #[expect(
        clippy::arithmetic_side_effects,
        reason = "blob hex capacity math operates on bounded message buffers"
    )]
    fn db_value_to_sql(value: &DbValue) -> String {
        match value {
            DbValue::Null => "NULL".to_string(),
            DbValue::Bool(b) => if *b { "1" } else { "0" }.to_string(),
            DbValue::Int(i) => i.to_string(),
            DbValue::Float(f) => f.to_string(),
            DbValue::Text(s) => format!("'{}'", s.replace('\'', "''")),
            DbValue::Blob(b) => {
                use std::fmt::Write;
                let mut hex = String::with_capacity(b.len() * 2 + 3);
                hex.push_str("X'");
                for byte in b {
                    // `fmt::Error` is `Copy`, so `drop()` would itself trip
                    // `clippy::dropping_copy_types`; writing into a `String`
                    // via `fmt::Write` never actually fails.
                    #[expect(
                        clippy::let_underscore_must_use,
                        reason = "fmt::Write to a String is infallible in practice"
                    )]
                    let _ = write!(hex, "{byte:02x}");
                }
                hex.push('\'');
                hex
            }
        }
    }

    fn build_create_index_sql(index: &ene_plugin_db::DbIndex) -> String {
        let columns = index.columns.join(", ");
        let unique = if index.unique { "UNIQUE " } else { "" };
        format!(
            "CREATE {unique}INDEX IF NOT EXISTS {} ON {} ({})",
            index.name, index.table, columns
        )
    }

    fn db_value_to_sea_value(val: &DbValue) -> sea_orm::Value {
        match val {
            DbValue::Null => sea_orm::Value::from(None::<i32>),
            DbValue::Bool(b) => sea_orm::Value::from(*b),
            DbValue::Int(i) => sea_orm::Value::from(*i),
            DbValue::Float(f) => sea_orm::Value::from(*f),
            DbValue::Text(s) => sea_orm::Value::from(s.clone()),
            DbValue::Blob(b) => sea_orm::Value::from(b.clone()),
        }
    }

    #[expect(
        clippy::indexing_slicing,
        reason = "indexes into request-owned row map with validated column keys"
    )]
    async fn handle_insert(
        db: &DatabaseConnection,
        table: &str,
        row: Row,
    ) -> Result<i64, DbServerError> {
        let mut insert = Query::insert();
        insert.into_table(Alias::new(table));

        let columns: Vec<String> = row.keys().cloned().collect();
        insert.columns(columns.iter().map(Alias::new));

        let values: Vec<sea_orm::sea_query::SimpleExpr> = columns
            .iter()
            .map(|k| Self::db_value_to_sea_value(&row[k]).into())
            .collect();

        insert
            .values(values)
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        let (sql, params) = insert.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let exec_res = db
            .execute_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        Ok(exec_res.last_insert_id() as i64)
    }

    #[expect(
        clippy::indexing_slicing,
        reason = "indexes into request-owned row map with validated column keys"
    )]
    async fn handle_upsert(
        db: &DatabaseConnection,
        table: &str,
        row: Row,
        conflict_columns: Vec<String>,
    ) -> Result<i64, DbServerError> {
        let mut insert = Query::insert();
        insert.into_table(Alias::new(table));

        let columns: Vec<String> = row.keys().cloned().collect();
        insert.columns(columns.iter().map(Alias::new));

        let values: Vec<sea_orm::sea_query::SimpleExpr> = columns
            .iter()
            .map(|k| Self::db_value_to_sea_value(&row[k]).into())
            .collect();

        insert
            .values(values)
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        let mut on_conflict =
            sea_orm::sea_query::OnConflict::columns(conflict_columns.iter().map(Alias::new));

        let update_cols: Vec<Alias> = columns
            .iter()
            .filter(|c| !conflict_columns.contains(c))
            .map(Alias::new)
            .collect();

        if !update_cols.is_empty() {
            on_conflict.update_columns(update_cols);
            insert.on_conflict(on_conflict);
        }

        let (sql, params) = insert.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let exec_res = db
            .execute_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        Ok(exec_res.last_insert_id() as i64)
    }

    async fn handle_select(
        db: &DatabaseConnection,
        declared_tables: &HashMap<String, DbTable>,
        declared_columns: &HashMap<String, HashSet<String>>,
        table: &str,
        columns: Vec<String>,
        filter: DbFilter,
        order_by: Vec<DbOrderBy>,
        limit: Option<u64>,
    ) -> Result<Vec<Row>, DbServerError> {
        Self::validate_table_access(declared_tables, table)?;
        Self::validate_select_columns(declared_columns, table, &columns)?;
        Self::validate_filter_columns(declared_columns, table, &filter)?;
        Self::validate_order_by_columns(declared_columns, table, &order_by)?;

        let mut select = Query::select();
        select.from(Alias::new(table));

        if columns.is_empty() {
            select.column(sea_orm::sea_query::Asterisk);
        } else {
            for col in &columns {
                select.column(Alias::new(col));
            }
        }

        let cond = Self::build_sea_query_filter(&filter)?;
        select.cond_where(cond);

        for o in &order_by {
            let order = if matches!(o.direction, ene_plugin_db::DbOrderDirection::Desc) {
                sea_orm::sea_query::Order::Desc
            } else {
                sea_orm::sea_query::Order::Asc
            };
            select.order_by(Alias::new(&o.column), order);
        }

        if let Some(limit) = limit {
            select.limit(limit);
        }

        let (sql, params) = select.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let query_results = db
            .query_all_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        let cols_to_fetch = if columns.is_empty() {
            declared_columns.get(table).cloned().unwrap_or_default()
        } else {
            columns.into_iter().collect::<HashSet<_>>()
        };

        let table_def = declared_tables
            .get(table)
            .ok_or_else(|| DbServerError::UnknownTable(table.to_string()))?;

        let col_def_map: HashMap<&str, &ene_plugin_db::DbColumn> = table_def
            .columns
            .iter()
            .map(|c| (c.name.as_str(), c))
            .collect();

        let mut rows = Vec::new();
        for result in query_results {
            let mut row = Row::new();
            for col in &cols_to_fetch {
                let col_def = col_def_map.get(col.as_str());
                let val = if let Some(def) = col_def {
                    match def.ty {
                        ene_plugin_db::DbType::Integer => {
                            if let Ok(Some(v)) = result.try_get::<Option<i64>>("", col) {
                                DbValue::Int(v)
                            } else {
                                DbValue::Null
                            }
                        }
                        ene_plugin_db::DbType::Real => {
                            if let Ok(Some(v)) = result.try_get::<Option<f64>>("", col) {
                                DbValue::Float(v)
                            } else {
                                DbValue::Null
                            }
                        }
                        ene_plugin_db::DbType::Text => {
                            if let Ok(Some(v)) = result.try_get::<Option<String>>("", col) {
                                DbValue::Text(v)
                            } else {
                                DbValue::Null
                            }
                        }
                        ene_plugin_db::DbType::Blob => {
                            if let Ok(Some(v)) = result.try_get::<Option<Vec<u8>>>("", col) {
                                DbValue::Blob(v)
                            } else {
                                DbValue::Null
                            }
                        }
                        ene_plugin_db::DbType::Boolean => {
                            if let Ok(Some(v)) = result.try_get::<Option<bool>>("", col) {
                                DbValue::Bool(v)
                            } else if let Ok(Some(v)) = result.try_get::<Option<i64>>("", col) {
                                DbValue::Bool(v != 0)
                            } else {
                                DbValue::Null
                            }
                        }
                    }
                } else {
                    DbValue::Null
                };
                row.insert(col.clone(), val);
            }
            rows.push(row);
        }

        Ok(rows)
    }

    #[expect(
        clippy::indexing_slicing,
        reason = "indexes into request-owned set map with validated column keys"
    )]
    async fn handle_update(
        db: &DatabaseConnection,
        table: &str,
        set: Row,
        filter: DbFilter,
    ) -> Result<u64, DbServerError> {
        let mut update = Query::update();
        update.table(Alias::new(table));

        let columns: Vec<String> = set.keys().cloned().collect();
        let values: Vec<sea_orm::Value> = columns
            .iter()
            .map(|k| Self::db_value_to_sea_value(&set[k]))
            .collect();

        for (col, val) in columns.iter().zip(values) {
            update.value(Alias::new(col), Expr::val(val));
        }

        let cond = Self::build_sea_query_filter(&filter)?;
        update.cond_where(cond);

        let (sql, params) = update.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let exec_res = db
            .execute_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        Ok(exec_res.rows_affected())
    }

    async fn handle_delete(
        db: &DatabaseConnection,
        table: &str,
        filter: DbFilter,
    ) -> Result<u64, DbServerError> {
        let mut delete = Query::delete();
        delete.from_table(Alias::new(table));

        let cond = Self::build_sea_query_filter(&filter)?;
        delete.cond_where(cond);

        let (sql, params) = delete.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let exec_res = db
            .execute_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        Ok(exec_res.rows_affected())
    }

    async fn handle_count(
        db: &DatabaseConnection,
        table: &str,
        filter: DbFilter,
    ) -> Result<i64, DbServerError> {
        let mut select = Query::select();
        select.from(Alias::new(table));
        select.expr_as(Expr::cust("COUNT(*)"), Alias::new("count"));

        let cond = Self::build_sea_query_filter(&filter)?;
        select.cond_where(cond);

        let (sql, params) = select.build(SqliteQueryBuilder);
        let stmt = Statement::from_sql_and_values(DatabaseBackend::Sqlite, &sql, params);

        let res = db
            .query_one_raw(stmt)
            .await
            .map_err(|e| DbServerError::Internal(e.to_string()))?;

        let count: i64 = match res {
            Some(row) => row.try_get("", "count").unwrap_or(0),
            None => 0,
        };

        Ok(count)
    }

    fn build_sea_query_filter(filter: &DbFilter) -> Result<Condition, DbServerError> {
        match filter {
            DbFilter::Always => Ok(Condition::all()),
            DbFilter::And(filters) => {
                let mut cond = Condition::all();
                for f in filters {
                    cond = cond.add(Self::build_sea_query_filter(f)?);
                }
                Ok(cond)
            }
            DbFilter::Or(filters) => {
                let mut cond = Condition::any();
                for f in filters {
                    cond = cond.add(Self::build_sea_query_filter(f)?);
                }
                Ok(cond)
            }
            DbFilter::Not(f) => {
                let inner = Self::build_sea_query_filter(f)?;
                Ok(Condition::all().not().add(inner))
            }
            DbFilter::Eq { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).eq(Self::db_value_to_sea_value(value)))),
            DbFilter::Ne { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).ne(Self::db_value_to_sea_value(value)))),
            DbFilter::Lt { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).lt(Self::db_value_to_sea_value(value)))),
            DbFilter::Le { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).lte(Self::db_value_to_sea_value(value)))),
            DbFilter::Gt { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).gt(Self::db_value_to_sea_value(value)))),
            DbFilter::Ge { column, value } => Ok(Condition::all()
                .add(Expr::col(Alias::new(column)).gte(Self::db_value_to_sea_value(value)))),
            DbFilter::In { column, values } => {
                let sea_vals: Vec<sea_orm::Value> =
                    values.iter().map(Self::db_value_to_sea_value).collect();
                Ok(Condition::all().add(Expr::col(Alias::new(column)).is_in(sea_vals)))
            }
            DbFilter::Like { column, pattern } => {
                Ok(Condition::all().add(Expr::col(Alias::new(column)).like(pattern.clone())))
            }
            DbFilter::IsNull { column } => {
                Ok(Condition::all().add(Expr::col(Alias::new(column)).is_null()))
            }
            DbFilter::IsNotNull { column } => {
                Ok(Condition::all().add(Expr::col(Alias::new(column)).is_not_null()))
            }
        }
    }
}

/// Additive differences between a stored schema declaration and a new one.
///
/// Produced by [`DbIpcServer::diff_schemas`]; consumed by
/// [`DbIpcServer::apply_schema_change`] to migrate the physical tables in
/// place. Only additions are representable — removals and type changes are
/// reported as errors before a `SchemaDiff` is built.
#[derive(Debug, Default)]
struct SchemaDiff {
    /// Tables present in the new declaration but absent from the stored one.
    added_tables: Vec<DbTable>,
    /// Columns added to already-existing tables, paired with their table.
    added_columns: Vec<(DbTable, DbColumn)>,
}

#[cfg(test)]
#[expect(
    clippy::similar_names,
    clippy::iter_on_single_items,
    reason = "IPC test fixtures use paired request/response names and single-item iterators"
)]
mod tests {
    use super::*;

    #[test]
    fn validate_identifier_accepts_valid_names() {
        for name in [
            "fs_data",
            "_internal",
            "Table1",
            "a",
            "A_B_C_123",
            "x_1234567890_1234567890_1234567890_1234567890_1234567890_abcdefg",
        ] {
            assert!(
                DbIpcServer::validate_identifier(name).is_ok(),
                "expected '{name}' to be valid"
            );
        }
    }

    #[test]
    fn validate_identifier_rejects_injection_payloads() {
        // Each of these would be a valid SQL injection vector if interpolated
        // unescaped into a CREATE TABLE / CREATE INDEX statement.
        let bad_inputs = [
            "x) ; DROP TABLE fs_data; --",
            "evil\" TEXT --",
            "x'; DROP TABLE foo; --",
            "a; DROP TABLE users",
            "1col",          // starts with digit
            "with space",    // contains space
            "with-dash",     // contains dash
            "with`backtick", // contains backtick
            "",              // empty
            "table.name",    // contains dot
            "(select 1)",    // contains parens
            "x_1234567890_1234567890_1234567890_1234567890_1234567890_abcdefX1", // > 64
        ];
        for bad in bad_inputs {
            assert!(
                DbIpcServer::validate_identifier(bad).is_err(),
                "expected '{bad}' to be rejected"
            );
        }
    }

    #[test]
    fn build_create_table_sql_emits_valid_ddl() {
        let table = ene_plugin_db::DbTable {
            name: "fs_notes".to_string(),
            columns: vec![
                ene_plugin_db::DbColumn {
                    name: "id".to_string(),
                    ty: ene_plugin_db::DbType::Integer,
                    nullable: false,
                    primary_key: true,
                    auto_increment: true,
                    unique: false,
                    default: None,
                },
                ene_plugin_db::DbColumn {
                    name: "body".to_string(),
                    ty: ene_plugin_db::DbType::Text,
                    nullable: true,
                    primary_key: false,
                    auto_increment: false,
                    unique: false,
                    default: None,
                },
            ],
        };
        let sql = DbIpcServer::build_create_table_sql(&table);
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS fs_notes ("));
        assert!(sql.contains("id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT"));
        assert!(sql.contains("body TEXT"));
    }

    /// Regression test for #42: after an Insert, a
    /// `LastInsertRowId` request must return the rowid of
    /// that Insert — not 0 (the previous "no prior insert"
    /// sentinel) and not the rowid of some other insert
    /// served by a different pooled connection. The
    /// connection-scoped `last_rowid` cell records the
    /// rowid of the most recent Insert on this logical
    /// `handle_connection` and the dispatch returns it
    /// verbatim.
    #[tokio::test]
    async fn last_insert_rowid_returns_most_recent_insert() {
        use sea_orm::ConnectionTrait;
        let db = sea_orm::Database::connect("sqlite::memory:").await.unwrap();
        db.execute_unprepared(
            "CREATE TABLE fs_test (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)",
        )
        .await
        .unwrap();

        let mut declared_tables: HashMap<String, ene_plugin_db::DbTable> = HashMap::new();
        declared_tables.insert(
            "fs_test".to_string(),
            ene_plugin_db::DbTable {
                name: "fs_test".to_string(),
                columns: vec![ene_plugin_db::DbColumn {
                    name: "name".to_string(),
                    ty: ene_plugin_db::DbType::Text,
                    nullable: false,
                    primary_key: false,
                    auto_increment: false,
                    unique: false,
                    default: None,
                }],
            },
        );
        let mut declared_columns: HashMap<String, HashSet<String>> = HashMap::new();
        declared_columns.insert(
            "fs_test".to_string(),
            ["name".to_string()].into_iter().collect(),
        );

        let last_rowid: Arc<std::sync::Mutex<Option<i64>>> = Arc::new(std::sync::Mutex::new(None));

        // Insert a row.
        let insert_resp = DbIpcServer::handle_request(
            &db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            &last_rowid,
            ene_plugin_db::DbRequest::Insert {
                table: "fs_test".to_string(),
                row: std::collections::BTreeMap::from([(
                    "name".to_string(),
                    ene_plugin_db::DbValue::Text("first".to_string()),
                )]),
            },
        )
        .await;
        let first_id = match insert_resp {
            ene_plugin_db::DbResponse::Insert { rowid } => rowid,
            other => panic!("expected Insert, got {other:?}"),
        };
        assert!(first_id > 0);

        // LastInsertRowId must return the rowid we just got.
        let lookup = DbIpcServer::handle_request(
            &db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            &last_rowid,
            ene_plugin_db::DbRequest::LastInsertRowId,
        )
        .await;
        let lookup_id = match lookup {
            ene_plugin_db::DbResponse::LastInsertRowId { rowid } => rowid,
            other => panic!("expected LastInsertRowId, got {other:?}"),
        };
        assert_eq!(lookup_id, first_id);

        // Insert a second row; LastInsertRowId now points
        // at the new row.
        let insert_resp2 = DbIpcServer::handle_request(
            &db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            &last_rowid,
            ene_plugin_db::DbRequest::Insert {
                table: "fs_test".to_string(),
                row: std::collections::BTreeMap::from([(
                    "name".to_string(),
                    ene_plugin_db::DbValue::Text("second".to_string()),
                )]),
            },
        )
        .await;
        let second_id = match insert_resp2 {
            ene_plugin_db::DbResponse::Insert { rowid } => rowid,
            other => panic!("expected Insert, got {other:?}"),
        };
        assert!(second_id > first_id);

        let lookup2 = DbIpcServer::handle_request(
            &db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            &last_rowid,
            ene_plugin_db::DbRequest::LastInsertRowId,
        )
        .await;
        let lookup2_id = match lookup2 {
            ene_plugin_db::DbResponse::LastInsertRowId { rowid } => rowid,
            other => panic!("expected LastInsertRowId, got {other:?}"),
        };
        assert_eq!(lookup2_id, second_id);
    }

    // --- Schema fingerprint / evolution tests (#423) ---

    fn test_column(name: &str, ty: ene_plugin_db::DbType) -> ene_plugin_db::DbColumn {
        ene_plugin_db::DbColumn {
            name: name.to_string(),
            ty,
            nullable: true,
            primary_key: false,
            auto_increment: false,
            unique: false,
            default: None,
        }
    }

    fn test_schema_v1() -> ene_plugin_db::DbSchema {
        ene_plugin_db::DbSchema {
            prefix: "fs_".to_string(),
            tables: vec![ene_plugin_db::DbTable {
                name: "fs_undo".to_string(),
                columns: vec![
                    test_column("id", ene_plugin_db::DbType::Integer),
                    test_column("path", ene_plugin_db::DbType::Text),
                ],
            }],
            indexes: Vec::new(),
        }
    }

    /// Creates an in-memory DB with the `__tool_schemas` bookkeeping table.
    async fn test_db_with_tool_schemas() -> sea_orm::DatabaseConnection {
        let db = sea_orm::Database::connect("sqlite::memory:").await.unwrap();
        db.execute_unprepared(
            "CREATE TABLE __tool_schemas (prefix TEXT PRIMARY KEY NOT NULL, schema_json TEXT NOT NULL, fingerprint TEXT NOT NULL, created_at TEXT NOT NULL)",
        )
        .await
        .unwrap();
        db
    }

    async fn declare(
        db: &sea_orm::DatabaseConnection,
        schema: ene_plugin_db::DbSchema,
    ) -> DbResponse {
        let mut declared_tables = HashMap::new();
        let mut declared_columns = HashMap::new();
        DbIpcServer::handle_declare_schema(
            db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            schema,
        )
        .await
        .unwrap_or_else(|e| e.to_error_response())
    }

    async fn stored_row(
        db: &sea_orm::DatabaseConnection,
        prefix: &str,
    ) -> Option<tool_schemas::Model> {
        tool_schemas::Entity::find_by_id(prefix)
            .one(db)
            .await
            .unwrap()
    }

    async fn table_columns(db: &sea_orm::DatabaseConnection, table: &str) -> Vec<String> {
        let rows = db
            .query_all_raw(Statement::from_string(
                DatabaseBackend::Sqlite,
                format!("PRAGMA table_info({table})"),
            ))
            .await
            .unwrap();
        rows.iter()
            .map(|r| r.try_get::<String>("", "name").unwrap())
            .collect()
    }

    async fn insert_row(
        db: &sea_orm::DatabaseConnection,
        table: &str,
        row: Row,
        declared_tables: &HashMap<String, ene_plugin_db::DbTable>,
        declared_columns: &HashMap<String, HashSet<String>>,
    ) -> DbResponse {
        let last_rowid: Arc<std::sync::Mutex<Option<i64>>> = Arc::new(std::sync::Mutex::new(None));
        let mut declared_tables = declared_tables.clone();
        let mut declared_columns = declared_columns.clone();
        DbIpcServer::handle_request(
            db,
            "fs",
            "fs_",
            &mut declared_tables,
            &mut declared_columns,
            &last_rowid,
            ene_plugin_db::DbRequest::Insert {
                table: table.to_string(),
                row,
            },
        )
        .await
    }

    /// Registering a changed schema refreshes the stored row (fingerprint +
    /// `schema_json`) and applies the new column to the existing table.
    #[tokio::test]
    async fn changed_schema_updates_stored_row_and_applies_column() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));
        let row_v1 = stored_row(&db, "fs_").await.expect("row stored after v1");
        assert_eq!(
            table_columns(&db, "fs_undo").await,
            ["id".to_string(), "path".to_string()]
        );

        // v2 adds a `checksum` column to the existing `fs_undo` table.
        let mut schema_v2 = test_schema_v1();
        schema_v2.tables[0]
            .columns
            .push(test_column("checksum", ene_plugin_db::DbType::Text));

        let resp = declare(&db, schema_v2.clone()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // The stored declaration was refreshed to the new fingerprint/json.
        let row_v2 = stored_row(&db, "fs_").await.expect("row stored after v2");
        assert_ne!(row_v1.fingerprint, row_v2.fingerprint);
        assert_eq!(
            row_v2.schema_json,
            serde_json::to_string(&schema_v2).unwrap()
        );

        // The physical table gained the column, and existing rows survived.
        assert_eq!(
            table_columns(&db, "fs_undo").await,
            ["id".to_string(), "path".to_string(), "checksum".to_string()]
        );
    }

    /// Re-declaring an identical schema must not rewrite the stored row.
    #[tokio::test]
    async fn unchanged_schema_does_not_rewrite_stored_row() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));
        let first = stored_row(&db, "fs_").await.expect("row stored");

        // Ensure a rewrite would produce a different `created_at`.
        tokio::time::sleep(std::time::Duration::from_millis(20)).await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));
        let second = stored_row(&db, "fs_").await.expect("row still stored");

        assert_eq!(first.fingerprint, second.fingerprint);
        assert_eq!(first.schema_json, second.schema_json);
        assert_eq!(first.created_at, second.created_at);
    }

    /// A column type change cannot be applied in place and is rejected.
    #[tokio::test]
    async fn type_change_is_rejected_as_conflict() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));
        let before = stored_row(&db, "fs_").await.expect("row stored");

        // v2 changes `path` from TEXT to INTEGER.
        let mut schema_v2 = test_schema_v1();
        schema_v2.tables[0].columns[1].ty = ene_plugin_db::DbType::Integer;

        let resp = declare(&db, schema_v2).await;
        assert!(
            matches!(
                resp,
                DbResponse::Error {
                    code: DbErrorCode::SchemaConflict,
                    ..
                }
            ),
            "expected SchemaConflict, got {resp:?}"
        );

        // The stored declaration is untouched after the rejected change.
        let after = stored_row(&db, "fs_").await.expect("row still stored");
        assert_eq!(before.fingerprint, after.fingerprint);
        assert_eq!(before.schema_json, after.schema_json);
    }

    /// Removing a previously declared table is rejected rather than silently
    /// leaving the physical table orphaned.
    #[tokio::test]
    async fn removed_table_is_rejected_as_conflict() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // v2 drops the `fs_undo` table entirely.
        let schema_v2 = ene_plugin_db::DbSchema {
            prefix: "fs_".to_string(),
            tables: Vec::new(),
            indexes: Vec::new(),
        };

        let resp = declare(&db, schema_v2).await;
        assert!(
            matches!(
                resp,
                DbResponse::Error {
                    code: DbErrorCode::SchemaConflict,
                    ..
                }
            ),
            "expected SchemaConflict, got {resp:?}"
        );
    }

    /// Removing a column from an existing table is rejected rather than
    /// leaving the physical column orphaned.
    #[tokio::test]
    async fn removed_column_is_rejected_as_conflict() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // v2 drops the `path` column from `fs_undo`.
        let mut schema_v2 = test_schema_v1();
        schema_v2.tables[0].columns.pop();

        let resp = declare(&db, schema_v2).await;
        assert!(
            matches!(
                resp,
                DbResponse::Error {
                    code: DbErrorCode::SchemaConflict,
                    ..
                }
            ),
            "expected SchemaConflict, got {resp:?}"
        );
    }

    /// Adding a column that carries a `UNIQUE` constraint is rejected, since
    /// `SQLite` cannot add a constrained column via `ALTER TABLE`.
    #[tokio::test]
    async fn added_unique_column_is_rejected_as_conflict() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // v2 adds a UNIQUE column, which ALTER TABLE ADD COLUMN forbids.
        let mut schema_v2 = test_schema_v1();
        let mut unique_col = test_column("slug", ene_plugin_db::DbType::Text);
        unique_col.unique = true;
        schema_v2.tables[0].columns.push(unique_col);

        let resp = declare(&db, schema_v2).await;
        assert!(
            matches!(
                resp,
                DbResponse::Error {
                    code: DbErrorCode::SchemaConflict,
                    ..
                }
            ),
            "expected SchemaConflict, got {resp:?}"
        );
    }

    /// An additive migration preserves existing rows and accepts new data in
    /// the added column — the exact scenario from #423.
    #[tokio::test]
    async fn additive_migration_preserves_existing_rows() {
        let db = test_db_with_tool_schemas().await;

        let resp = declare(&db, test_schema_v1()).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // Insert a row under the v1 schema.
        let declared_tables: HashMap<String, ene_plugin_db::DbTable> = test_schema_v1()
            .tables
            .into_iter()
            .map(|t| (t.name.clone(), t))
            .collect();
        let declared_columns: HashMap<String, HashSet<String>> = declared_tables
            .iter()
            .map(|(name, t)| {
                (
                    name.clone(),
                    t.columns.iter().map(|c| c.name.clone()).collect(),
                )
            })
            .collect();
        let resp = insert_row(
            &db,
            "fs_undo",
            std::collections::BTreeMap::from([(
                "path".to_string(),
                ene_plugin_db::DbValue::Text("/tmp/a".to_string()),
            )]),
            &declared_tables,
            &declared_columns,
        )
        .await;
        assert!(matches!(resp, DbResponse::Insert { .. }));

        // Migrate to v2 (adds `checksum`).
        let mut schema_v2 = test_schema_v1();
        schema_v2.tables[0]
            .columns
            .push(test_column("checksum", ene_plugin_db::DbType::Text));
        let resp = declare(&db, schema_v2).await;
        assert!(matches!(resp, DbResponse::SchemaAccepted { .. }));

        // The existing row survived; the new column reads back as NULL.
        let rows = db
            .query_all_raw(Statement::from_string(
                DatabaseBackend::Sqlite,
                "SELECT path, checksum FROM fs_undo".to_string(),
            ))
            .await
            .unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(
            rows[0].try_get::<String>("", "path").unwrap(),
            "/tmp/a".to_string()
        );
        assert!(
            rows[0]
                .try_get::<Option<String>>("", "checksum")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn build_alter_add_column_sql_renders_type_and_default() {
        let table = ene_plugin_db::DbTable {
            name: "fs_undo".to_string(),
            columns: Vec::new(),
        };

        let nullable = test_column("checksum", ene_plugin_db::DbType::Text);
        assert_eq!(
            DbIpcServer::build_alter_add_column_sql(&table, &nullable),
            "ALTER TABLE fs_undo ADD COLUMN checksum TEXT"
        );

        let with_default = ene_plugin_db::DbColumn {
            name: "count".to_string(),
            ty: ene_plugin_db::DbType::Integer,
            nullable: false,
            primary_key: false,
            auto_increment: false,
            unique: false,
            default: Some(ene_plugin_db::DbValue::Int(0)),
        };
        assert_eq!(
            DbIpcServer::build_alter_add_column_sql(&table, &with_default),
            "ALTER TABLE fs_undo ADD COLUMN count INTEGER NOT NULL DEFAULT 0"
        );
    }
}
