use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::pin::Pin;
use std::sync::{Arc, Mutex, OnceLock};
use tokio_stream::{Stream, StreamExt};

use crate::config::TaskRef;
use crate::error::LlmProviderError;
use crate::message::{LlmCompletion, LlmMessage, LlmResponseChunk};

/// Trait implemented by LLM providers to interface with Ene.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Provider display name (e.g. `"openai"`, `"ollama"`).
    fn name(&self) -> &str;

    /// Context window the backend advertises for the active model, in tokens.
    ///
    /// `None` means the backend does not report a limit — an in-process
    /// provider that does not know its own window, or an older plugin binary
    /// that omits `LlmProviderSpec.context_window`. Callers reconcile this with
    /// any operator override via [`crate::context_window::effective_window`],
    /// which falls back to [`crate::context_window::DEFAULT_CONTEXT_WINDOW`]
    /// when neither source names a limit.
    fn context_window(&self) -> Option<u32> {
        None
    }

    /// Initiates a chat completion stream with the given messages and tools.
    async fn create_chat_stream(
        &self,
        messages: &[LlmMessage],
        tools: &[ene_plugin_proto::ToolSpec],
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<LlmResponseChunk, LlmProviderError>> + Send>>,
        LlmProviderError,
    >;

    /// Executes a non-streaming chat completion with optional JSON schema response.
    ///
    /// Returns an [`LlmCompletion`] carrying the assistant text plus any token
    /// usage the provider reported; `usage` is `None` when the provider
    /// does not report it.
    async fn chat_completion(
        &self,
        messages: &[LlmMessage],
        json_schema: Option<serde_json::Value>,
    ) -> Result<LlmCompletion, LlmProviderError>;

    /// Collect a full assistant reply from a streaming chat completion.
    ///
    /// `OpenRouter` and some OpenAI-compatible models respond reliably to streaming
    /// requests but may hang or exceed budgets on non-streaming `chat().create()`.
    ///
    /// Returns an [`LlmCompletion`]: the concatenated text plus any usage the
    /// provider attached to the stream's final chunk.
    async fn collect_stream_completion(
        &self,
        messages: &[LlmMessage],
    ) -> Result<LlmCompletion, LlmProviderError> {
        let mut stream = self.create_chat_stream(messages, &[]).await?;
        let mut content = String::new();
        let mut usage = None;
        while let Some(chunk_res) = stream.next().await {
            let chunk = chunk_res?;
            if let Some(delta) = chunk.text_delta {
                content.push_str(&delta);
            }
            if chunk.usage.is_some() {
                usage = chunk.usage;
            }
        }
        Ok(LlmCompletion {
            text: content,
            usage,
        })
    }
}

/// Distinguishes embedding use cases. Providers may apply different prefixes
/// or chunking strategies per kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EmbeddingKind {
    /// Concise tool or document summary text.
    Summary,
    /// Full description text (often long).
    Description,
    /// One embedding per capability / action within a mega-tool.
    Capability,
    /// One embedding per worked example.
    Example,
    /// Negative-keyword text (used for soft penalties in Tool RAG).
    Negative,
    /// User query, may use a different prefix than documents.
    Query,
    /// Hypothetical document generated by `HyDE`.
    Hyde,
}

/// Errors raised by embedding providers. Wraps transport, provider, and
/// local-init errors in a single enum so call sites can use a typed error
/// instead of `String`. Consumers should match on the variant rather than
/// parsing the message.
#[derive(Debug, thiserror::Error)]
pub enum EmbeddingError {
    /// The embedding model failed to initialize (e.g. GGUF load error).
    /// Distinct from `Provider`, which is for transport / API errors.
    #[error("embedding init error: {0}")]
    Init(String),
    /// The provider returned a malformed or empty response, or a transport
    /// error (HTTP 4xx/5xx, network failure) prevented the request.
    #[error("embedding provider error: {0}")]
    Provider(String),
    /// The supplied text is empty or whitespace-only. We
    /// refuse to produce an embedding for it because
    /// every implementation would either return the
    /// zero vector (which has undefined cosine
    /// similarity and silently pollutes the store) or
    /// fall back to a placeholder that does not
    /// represent the input.
    #[error("empty or whitespace-only input; cannot produce a meaningful embedding")]
    EmptyInput,
    /// Batch response length or per-vector dimensionality does not match
    /// the request / provider contract.
    #[error("embedding dimension or batch mismatch: {0}")]
    DimensionMismatch(String),
}

impl EmbeddingError {
    /// Whether this error is transient and may succeed on retry.
    ///
    /// Transport / API failures (`Provider`) are retryable; init, empty-input,
    /// and dimension-mismatch errors are deterministic and not retried.
    #[must_use]
    pub const fn is_retryable(&self) -> bool {
        matches!(self, Self::Provider(_))
    }
}

/// Trait for generating vector embeddings from text (used by memory search and Tool RAG).
///
/// The only embedding operation on this trait is [`embed_batch`]. Single-text and
/// query helpers are free functions ([`embed`], [`embed_query`]) that call
/// batch. `HyDE` and rerank live in pipeline helpers (`ene_rag::tool::hybrid`),
/// not on this trait.
#[async_trait]
pub trait EmbeddingProvider: Send + Sync {
    /// Batch embed. Implementations should saturate hardware (thread pool for
    /// GGUF, concurrent HTTP for cloud). Output order must match `items`.
    /// An empty `items` slice returns an empty `Vec`.
    async fn embed_batch(
        &self,
        items: &[(&str, EmbeddingKind)],
    ) -> Result<Vec<Vec<f32>>, EmbeddingError>;

    /// The dimensionality of the embedding vectors produced by this provider.
    fn dimensions(&self) -> usize;
    /// A human-readable name identifying the embedding model.
    fn model_name(&self) -> &str;
}

/// Embed a single piece of text via [`EmbeddingProvider::embed_batch`].
pub async fn embed<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
    kind: EmbeddingKind,
) -> Result<Vec<f32>, EmbeddingError> {
    let mut out = provider.embed_batch(&[(text, kind)]).await?;
    out.pop().ok_or_else(|| {
        EmbeddingError::DimensionMismatch(
            "embed_batch returned empty result for a single-item request".into(),
        )
    })
}

/// Embed a query via [`embed`] with [`EmbeddingKind::Query`].
pub async fn embed_query<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
) -> Result<Vec<f32>, EmbeddingError> {
    embed(provider, text, EmbeddingKind::Query).await
}

/// Cosine similarity between two vectors. Returns 0.0 for empty or norm-zero
/// inputs. Both vectors must have the same length for a meaningful result.
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.is_empty() || b.is_empty() {
        return 0.0;
    }
    if a.len() != b.len() {
        tracing::warn!(
            component = "cosine_similarity",
            a_len = a.len(),
            b_len = b.len(),
            "dimension mismatch; returning 0.0"
        );
        return 0.0;
    }
    let mut dot = 0.0_f64;
    let mut na = 0.0_f64;
    let mut nb = 0.0_f64;
    for (x, y) in a.iter().zip(b.iter()) {
        dot = f64::from(*x).mul_add(f64::from(*y), dot);
        na += f64::from(*x).powi(2);
        nb += f64::from(*y).powi(2);
    }
    let denom = (na * nb).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        (dot / denom) as f32
    }
}

/// Factory trait to build specific `LlmProvider` instances from workspace configs.
pub trait LlmProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    ///
    /// `task` carries the cognitive task's routing entry — its `model` and
    /// `max_tokens` overrides in particular — so providers can honor
    /// task-specific configuration (e.g. `Classifier` or `Proactive`) instead
    /// of silently falling back to the `tasks.chat` defaults.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
        task: &TaskRef,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError>;
}

/// Global registry of `LlmProviderFactory` implementations.
pub struct LlmProviderRegistry {
    factories: Mutex<HashMap<String, Arc<dyn LlmProviderFactory>>>,
}

impl LlmProviderRegistry {
    fn global() -> &'static Self {
        static REGISTRY: OnceLock<LlmProviderRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| Self {
            factories: Mutex::new(HashMap::new()),
        })
    }

    /// Registers a new provider factory.
    pub fn register(factory: Arc<dyn LlmProviderFactory>) {
        let name = factory.provider_name().to_string();
        if let Ok(mut guard) = Self::global().factories.lock() {
            guard.insert(name, factory);
        }
    }

    /// Removes a registered factory by provider name.
    ///
    /// Returns `true` when a factory was actually removed, `false` when no
    /// factory was registered under `name`. Deregistration is what lets a
    /// factory whose backing plugin has died or been unloaded be evicted, so
    /// [`create_provider`](Self::create_provider) can no longer select a
    /// stale entry that points at a dead process.
    pub fn deregister(name: &str) -> bool {
        let Ok(mut guard) = Self::global().factories.lock() else {
            tracing::warn!(
                component = "LlmProviderRegistry",
                provider = %name,
                "Cannot deregister provider factory because the registry lock is poisoned"
            );
            return false;
        };
        guard.remove(name).is_some()
    }

    /// Removes a factory only when `name` still points to `expected`.
    ///
    /// The identity check prevents one runtime handle from deregistering a
    /// replacement factory installed by another handle during concurrent host
    /// reconfiguration.
    pub fn deregister_if_matches(name: &str, expected: &Arc<dyn LlmProviderFactory>) -> bool {
        let Ok(mut guard) = Self::global().factories.lock() else {
            tracing::warn!(
                component = "LlmProviderRegistry",
                provider = %name,
                "Cannot conditionally deregister provider factory because the registry lock is poisoned"
            );
            return false;
        };
        if guard
            .get(name)
            .is_some_and(|registered| Arc::ptr_eq(registered, expected))
        {
            guard.remove(name).is_some()
        } else {
            false
        }
    }

    /// Snapshot of the currently registered provider names.
    ///
    /// Intended for diagnostics and tests; the registry is process-global, so
    /// the set can change immediately after this returns.
    #[must_use]
    #[cfg(test)]
    pub fn registered_names() -> Vec<String> {
        if let Ok(guard) = Self::global().factories.lock() {
            guard.keys().cloned().collect()
        } else {
            Vec::new()
        }
    }

    /// Tries to instantiate a provider by name using the registered factories.
    ///
    /// `task` is forwarded to the factory so the produced provider can honor
    /// the task's `model` and `max_tokens` overrides (see
    /// [`LlmProviderFactory::create_provider`]).
    pub fn create_provider(
        name: &str,
        config: &ene_config::EneConfig,
        task: &TaskRef,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError> {
        let factory = {
            if let Ok(guard) = Self::global().factories.lock() {
                guard.get(name).cloned()
            } else {
                None
            }
        };

        match factory {
            Some(f) => f.create_provider(config, task),
            None => Err(LlmProviderError::Provider(format!(
                "No LlmProviderFactory registered for provider name: '{name}'"
            ))),
        }
    }
}

#[cfg(test)]
mod registry_tests {
    use super::*;
    use crate::openai::OpenAiProviderFactory;

    /// A factory whose `create_provider` always fails with a recognizable
    /// error, so a lookup that resolves it can be told apart from the
    /// "no factory registered" error path.
    struct MarkerFactory {
        name: &'static str,
    }

    impl LlmProviderFactory for MarkerFactory {
        fn provider_name(&self) -> &str {
            self.name
        }

        fn create_provider(
            &self,
            _config: &ene_config::EneConfig,
            _task: &TaskRef,
        ) -> Result<Box<dyn LlmProvider>, LlmProviderError> {
            Err(LlmProviderError::LocalLlm("marker factory".to_string()))
        }
    }

    fn config() -> ene_config::EneConfig {
        ene_config::EneConfig::default()
    }

    fn task() -> TaskRef {
        TaskRef::default()
    }

    /// Assert that `result` is an `Err` and return it. Used instead of
    /// `expect_err` because the boxed provider type is not `Debug`.
    fn unwrap_err(result: Result<Box<dyn LlmProvider>, LlmProviderError>) -> LlmProviderError {
        match result {
            Ok(_) => panic!("expected an error, got Ok"),
            Err(e) => e,
        }
    }

    /// The registry is a process-global singleton shared across tests running
    /// in the same process, so every test uses a distinct provider name to
    /// avoid cross-test interference.
    #[test]
    fn register_then_deregister_makes_lookup_fail() {
        const NAME: &str = "registry-test-ephemeral";
        LlmProviderRegistry::register(Arc::new(MarkerFactory { name: NAME }));

        let err = unwrap_err(LlmProviderRegistry::create_provider(
            NAME,
            &config(),
            &task(),
        ));
        assert!(matches!(err, LlmProviderError::LocalLlm(_)));

        assert!(LlmProviderRegistry::deregister(NAME));
        assert!(!LlmProviderRegistry::registered_names().contains(&NAME.to_string()));

        let err = unwrap_err(LlmProviderRegistry::create_provider(
            NAME,
            &config(),
            &task(),
        ));
        match err {
            LlmProviderError::Provider(msg) => assert!(msg.contains(NAME)),
            other => panic!("expected Provider error, got {other:?}"),
        }
    }

    #[test]
    fn deregister_unknown_name_is_false() {
        assert!(!LlmProviderRegistry::deregister(
            "registry-test-never-registered"
        ));
    }

    #[test]
    fn conditional_deregister_preserves_a_replacement_factory() {
        const NAME: &str = "registry-test-replacement";
        let original: Arc<dyn LlmProviderFactory> = Arc::new(MarkerFactory { name: NAME });
        let replacement: Arc<dyn LlmProviderFactory> = Arc::new(MarkerFactory { name: NAME });

        LlmProviderRegistry::register(Arc::clone(&original));
        LlmProviderRegistry::register(Arc::clone(&replacement));

        assert!(!LlmProviderRegistry::deregister_if_matches(NAME, &original));
        let err = unwrap_err(LlmProviderRegistry::create_provider(
            NAME,
            &config(),
            &task(),
        ));
        assert!(matches!(err, LlmProviderError::LocalLlm(_)));
        assert!(LlmProviderRegistry::deregister(NAME));
    }

    #[test]
    fn built_in_openai_factory_name_remains_stable() {
        assert_eq!(OpenAiProviderFactory.provider_name(), "openai-compatible");
    }

    #[test]
    fn deregister_is_idempotent() {
        const NAME: &str = "registry-test-idempotent";
        LlmProviderRegistry::register(Arc::new(MarkerFactory { name: NAME }));
        assert!(LlmProviderRegistry::deregister(NAME));
        assert!(!LlmProviderRegistry::deregister(NAME));
    }

    #[test]
    fn reregister_after_deregister_restores_lookup() {
        const NAME: &str = "registry-test-reregister";
        LlmProviderRegistry::register(Arc::new(MarkerFactory { name: NAME }));
        assert!(LlmProviderRegistry::deregister(NAME));

        LlmProviderRegistry::register(Arc::new(MarkerFactory { name: NAME }));
        let err = unwrap_err(LlmProviderRegistry::create_provider(
            NAME,
            &config(),
            &task(),
        ));
        assert!(matches!(err, LlmProviderError::LocalLlm(_)));

        // Clean up so this name does not linger for other tests.
        assert!(LlmProviderRegistry::deregister(NAME));
    }
}

#[cfg(test)]
#[expect(
    clippy::float_cmp,
    clippy::indexing_slicing,
    reason = "tests assert exact float equality and fixed mock embedder indices"
)]
mod tests {
    use super::*;

    struct MockEmbedder {
        dims: usize,
    }

    #[async_trait]
    impl EmbeddingProvider for MockEmbedder {
        async fn embed_batch(
            &self,
            items: &[(&str, EmbeddingKind)],
        ) -> Result<Vec<Vec<f32>>, EmbeddingError> {
            let mut out = Vec::with_capacity(items.len());
            for (text, _) in items {
                if text.trim().is_empty() {
                    return Err(EmbeddingError::EmptyInput);
                }
                let mut v = vec![0.0_f32; self.dims];
                if let (Some(slot), Some(c)) = (v.first_mut(), text.chars().next()) {
                    *slot = f32::from(c as u8);
                }
                out.push(v);
            }
            Ok(out)
        }

        fn dimensions(&self) -> usize {
            self.dims
        }

        fn model_name(&self) -> &'static str {
            "mock"
        }
    }

    #[tokio::test]
    async fn embed_batch_preserves_order_and_empty() {
        let p = MockEmbedder { dims: 4 };
        assert!(p.embed_batch(&[]).await.unwrap().is_empty());
        let items = [
            ("alpha", EmbeddingKind::Query),
            ("beta", EmbeddingKind::Summary),
        ];
        let out = p.embed_batch(&items).await.unwrap();
        assert_eq!(out.len(), 2);
        assert_eq!(out[0][0], f32::from(b'a'));
        assert_eq!(out[1][0], f32::from(b'b'));
    }

    #[tokio::test]
    async fn embed_and_embed_query_wrappers() {
        let p = MockEmbedder { dims: 3 };
        let v = embed(&p, "hello", EmbeddingKind::Summary).await.unwrap();
        assert_eq!(v.len(), 3);
        let q = embed_query(&p, "hello").await.unwrap();
        assert_eq!(q.len(), 3);
        assert!(matches!(
            embed(&p, "   ", EmbeddingKind::Query).await,
            Err(EmbeddingError::EmptyInput)
        ));
    }

    #[test]
    fn cosine_similarity_dimension_mismatch_is_zero() {
        assert_eq!(cosine_similarity(&[1.0, 0.0], &[1.0]), 0.0);
        assert_eq!(cosine_similarity(&[], &[1.0]), 0.0);
    }
}

// ── Audio provider traits (TTS / STT / VAD) ──────────────────────────────

/// Errors returned by audio provider implementations at the library boundary.
#[derive(Debug, thiserror::Error)]
pub enum AudioProviderError {
    /// The audio backend failed to initialize (model load, device open).
    #[error("audio init error: {0}")]
    Init(String),
    /// The provider encountered an error during synthesis or transcription.
    #[error("audio provider error: {0}")]
    Provider(String),
    /// The requested audio format or sample rate is not supported.
    #[error("unsupported audio format: {0}")]
    UnsupportedFormat(String),
    /// The operation timed out.
    #[error("audio operation timed out")]
    Timeout,
    /// An underlying I/O operation failed (file read, dylib load).
    #[error("audio I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// A local engine's bounded job queue was full
    /// (`ene_infer::EngineError::Busy`). Enqueue contention only — the
    /// engine itself is fine.
    #[error("engine busy: queue depth {queue_depth} exceeded")]
    Busy {
        /// The engine's configured queue depth at the time of the call.
        queue_depth: usize,
    },
    /// A local engine's job was cancelled (`ene_infer::EngineError::Cancelled`),
    /// either by an explicit cancellation or because the caller went away.
    #[error("local engine job cancelled")]
    Cancelled,
}

impl AudioProviderError {
    /// Whether this error is transient and may succeed on retry.
    ///
    /// `Busy` and `Timeout` are retryable, mirroring
    /// `ene_infer::EngineError::is_retryable`. `Cancelled` reflects caller
    /// intent, not engine health, so it is conservatively reported as not
    /// retryable. All other variants are deterministic or provider-specific
    /// and not retried.
    #[must_use]
    pub const fn is_retryable(&self) -> bool {
        matches!(self, Self::Busy { .. } | Self::Timeout)
    }
}

/// A chunk of synthesized PCM audio from a TTS provider.
#[derive(Debug, Clone, PartialEq)]
pub struct TtsChunk {
    /// Interleaved mono PCM samples normalized to `[-1.0, 1.0]`.
    pub pcm: Vec<f32>,
    /// Sample rate in Hz (e.g. 24000).
    pub sample_rate: u32,
}

/// Trait implemented by text-to-speech providers.
#[async_trait]
pub trait TtsProvider: Send + Sync {
    /// Provider display name (e.g. `"kokoro"`, `"openai"`).
    fn name(&self) -> &str;

    /// Synthesize text into a stream of PCM audio chunks.
    async fn synthesize_stream(
        &self,
        text: &str,
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<TtsChunk, AudioProviderError>> + Send>>,
        AudioProviderError,
    >;

    /// Synthesize text and collect all PCM chunks.
    ///
    /// Default implementation collects [`synthesize_stream`](Self::synthesize_stream).
    async fn synthesize(&self, text: &str) -> Result<Vec<TtsChunk>, AudioProviderError> {
        let mut stream = self.synthesize_stream(text).await?;
        let mut chunks = Vec::new();
        while let Some(chunk) = stream.next().await {
            chunks.push(chunk?);
        }
        Ok(chunks)
    }
}

/// Result of a speech-to-text transcription.
#[derive(Debug, Clone, PartialEq)]
pub struct SttResult {
    /// Transcribed text.
    pub text: String,
    /// Detected language code (e.g. `"ja"`, `"en"`), if available.
    pub language: Option<String>,
    /// Duration of the transcribed audio in seconds.
    pub duration_secs: f32,
}

/// Trait implemented by speech-to-text providers.
#[async_trait]
pub trait SttProvider: Send + Sync {
    /// Provider display name (e.g. `"whisper"`, `"openai"`).
    fn name(&self) -> &str;

    /// Transcribe PCM audio to text.
    async fn transcribe(
        &self,
        pcm: &[f32],
        sample_rate: u32,
    ) -> Result<SttResult, AudioProviderError>;
}

/// Voice activity detection event emitted per processed chunk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VadEvent {
    /// Speech just started.
    SpeechStart,
    /// Speech is continuing.
    SpeechContinue,
    /// Speech just ended.
    SpeechEnd,
    /// No speech detected.
    Silence,
}

/// Trait implemented by voice activity detection engines.
///
/// Engines are stateful (`&mut self`) and process fixed-size PCM chunks
/// sequentially. Not `Sync` because internal state is mutated per chunk.
///
/// # Frame-size contract
///
/// Each engine consumes frames of a fixed length reported by
/// [`frame_size`](Self::frame_size) (e.g. Silero VAD expects 512 samples at
/// 16 kHz / 32 ms). Callers must accumulate microphone PCM into exactly
/// [`frame_size`](Self::frame_size) samples before each
/// [`process_chunk`](Self::process_chunk) call. Passing a slice of any other
/// length is a programming error and [`process_chunk`](Self::process_chunk)
/// returns [`AudioProviderError::Provider`].
pub trait VadEngine: Send {
    /// Number of PCM samples expected per [`process_chunk`](Self::process_chunk) call.
    fn frame_size(&self) -> usize;

    /// Process a single [`frame_size`](Self::frame_size)-sample chunk of PCM
    /// audio and return the current VAD event.
    ///
    /// # Errors
    ///
    /// Returns [`AudioProviderError::Provider`] when `pcm.len()` does not equal
    /// [`frame_size`](Self::frame_size), or when the underlying inference step
    /// fails repeatedly (see the engine implementation for escalation policy).
    fn process_chunk(&mut self, pcm: &[f32]) -> Result<VadEvent, AudioProviderError>;

    /// Reset the engine to its initial state.
    fn reset(&mut self);

    /// Engine display name (e.g. `"silero"`, `"webrtc"`).
    fn name(&self) -> &str;
}

/// Factory trait to build [`TtsProvider`] instances from workspace configs.
pub trait TtsProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn TtsProvider>, AudioProviderError>;
}

/// Factory trait to build [`SttProvider`] instances from workspace configs.
pub trait SttProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn SttProvider>, AudioProviderError>;
}

/// Factory trait to build [`VadEngine`] instances from workspace configs.
pub trait VadFactory: Send + Sync {
    /// The unique name of the engine this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the engine based on current `EneConfig` settings.
    fn create_engine(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn VadEngine>, AudioProviderError>;
}

/// Global registry of audio provider factories (TTS, STT, VAD).
///
/// Uses the same `OnceLock` + `Mutex` pattern as
/// [`LlmProviderRegistry`] with separate
/// maps per modality. Locks use [`parking_lot::Mutex`] (poison-free, so no
/// poisoning checks are required at the call sites).
pub struct AudioProviderRegistry {
    tts: parking_lot::Mutex<HashMap<String, Arc<dyn TtsProviderFactory>>>,
    stt: parking_lot::Mutex<HashMap<String, Arc<dyn SttProviderFactory>>>,
    vad: parking_lot::Mutex<HashMap<String, Arc<dyn VadFactory>>>,
}

impl AudioProviderRegistry {
    fn global() -> &'static Self {
        static REGISTRY: OnceLock<AudioProviderRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| Self {
            tts: parking_lot::Mutex::new(HashMap::new()),
            stt: parking_lot::Mutex::new(HashMap::new()),
            vad: parking_lot::Mutex::new(HashMap::new()),
        })
    }

    /// Registers a TTS provider factory.
    pub fn register_tts(factory: Arc<dyn TtsProviderFactory>) {
        let name = factory.provider_name().to_string();
        Self::global().tts.lock().insert(name, factory);
    }

    /// Registers an STT provider factory.
    pub fn register_stt(factory: Arc<dyn SttProviderFactory>) {
        let name = factory.provider_name().to_string();
        Self::global().stt.lock().insert(name, factory);
    }

    /// Registers a VAD engine factory.
    pub fn register_vad(factory: Arc<dyn VadFactory>) {
        let name = factory.provider_name().to_string();
        Self::global().vad.lock().insert(name, factory);
    }

    /// Tries to instantiate a TTS provider by name using the registered factories.
    ///
    /// # Errors
    ///
    /// Returns [`AudioProviderError::Provider`] if no factory is registered for
    /// `name`, or the factory's own error if initialization fails.
    pub fn create_tts_provider(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn TtsProvider>, AudioProviderError> {
        let factory = Self::global().tts.lock().get(name).cloned();
        match factory {
            Some(f) => f.create_provider(config),
            None => Err(AudioProviderError::Provider(format!(
                "No TtsProviderFactory registered for provider name: '{name}'"
            ))),
        }
    }

    /// Tries to instantiate an STT provider by name using the registered factories.
    ///
    /// # Errors
    ///
    /// Returns [`AudioProviderError::Provider`] if no factory is registered for
    /// `name`, or the factory's own error if initialization fails.
    pub fn create_stt_provider(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn SttProvider>, AudioProviderError> {
        let factory = Self::global().stt.lock().get(name).cloned();
        match factory {
            Some(f) => f.create_provider(config),
            None => Err(AudioProviderError::Provider(format!(
                "No SttProviderFactory registered for provider name: '{name}'"
            ))),
        }
    }

    /// Tries to instantiate a VAD engine by name using the registered factories.
    ///
    /// # Errors
    ///
    /// Returns [`AudioProviderError::Provider`] if no factory is registered for
    /// `name`, or the factory's own error if initialization fails.
    pub fn create_vad_engine(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn VadEngine>, AudioProviderError> {
        let factory = Self::global().vad.lock().get(name).cloned();
        match factory {
            Some(f) => f.create_engine(config),
            None => Err(AudioProviderError::Provider(format!(
                "No VadFactory registered for provider name: '{name}'"
            ))),
        }
    }
}

#[cfg(test)]
mod audio_tests {
    use super::*;
    use std::sync::Arc;

    struct DummyTtsFactory;

    impl TtsProviderFactory for DummyTtsFactory {
        fn provider_name(&self) -> &'static str {
            "dummy-tts"
        }

        fn create_provider(
            &self,
            _config: &ene_config::EneConfig,
        ) -> Result<Box<dyn TtsProvider>, AudioProviderError> {
            Err(AudioProviderError::Init("dummy".to_string()))
        }
    }

    struct DummySttFactory;

    impl SttProviderFactory for DummySttFactory {
        fn provider_name(&self) -> &'static str {
            "dummy-stt"
        }

        fn create_provider(
            &self,
            _config: &ene_config::EneConfig,
        ) -> Result<Box<dyn SttProvider>, AudioProviderError> {
            Err(AudioProviderError::Init("dummy".to_string()))
        }
    }

    struct DummyVadFactory;

    impl VadFactory for DummyVadFactory {
        fn provider_name(&self) -> &'static str {
            "dummy-vad"
        }

        fn create_engine(
            &self,
            _config: &ene_config::EneConfig,
        ) -> Result<Box<dyn VadEngine>, AudioProviderError> {
            Err(AudioProviderError::Init("dummy".to_string()))
        }
    }

    fn config() -> ene_config::EneConfig {
        ene_config::EneConfig::default()
    }

    /// Assert that `result` is an `Err` and return it. Used instead of
    /// `expect_err` because the boxed provider types are not `Debug`.
    fn unwrap_err<T>(result: Result<T, AudioProviderError>) -> AudioProviderError {
        match result {
            Ok(_) => panic!("expected an error, got Ok"),
            Err(e) => e,
        }
    }

    #[test]
    fn tts_registration_lookup_round_trip() {
        AudioProviderRegistry::register_tts(Arc::new(DummyTtsFactory));
        let err = unwrap_err(AudioProviderRegistry::create_tts_provider(
            "dummy-tts",
            &config(),
        ));
        assert!(matches!(err, AudioProviderError::Init(_)));
    }

    #[test]
    fn stt_registration_lookup_round_trip() {
        AudioProviderRegistry::register_stt(Arc::new(DummySttFactory));
        let err = unwrap_err(AudioProviderRegistry::create_stt_provider(
            "dummy-stt",
            &config(),
        ));
        assert!(matches!(err, AudioProviderError::Init(_)));
    }

    #[test]
    fn vad_registration_lookup_round_trip() {
        AudioProviderRegistry::register_vad(Arc::new(DummyVadFactory));
        let err = unwrap_err(AudioProviderRegistry::create_vad_engine(
            "dummy-vad",
            &config(),
        ));
        assert!(matches!(err, AudioProviderError::Init(_)));
    }

    #[test]
    fn unknown_provider_name_errors() {
        let err = unwrap_err(AudioProviderRegistry::create_tts_provider(
            "does-not-exist",
            &config(),
        ));
        assert!(matches!(err, AudioProviderError::Provider(_)));
    }

    #[test]
    fn io_error_converts_via_from() {
        let io_err = std::io::Error::new(std::io::ErrorKind::NotFound, "missing");
        let err: AudioProviderError = io_err.into();
        assert!(matches!(err, AudioProviderError::Io(_)));
    }
}
