use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::pin::Pin;
use std::sync::{Arc, Mutex, OnceLock};
use tokio_stream::{Stream, StreamExt};

use crate::error::LlmProviderError;
use crate::message::{LlmMessage, LlmResponseChunk};

/// Trait implemented by LLM providers to interface with Ene.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Returns the unique name of this provider.
    fn name(&self) -> &str;

    /// Initiates a chat completion stream with the given messages and tools.
    async fn create_chat_stream(
        &self,
        messages: &[LlmMessage],
        tools: &[ene_tool_proto::ToolSpec],
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<LlmResponseChunk, LlmProviderError>> + Send>>,
        LlmProviderError,
    >;

    /// Executes a non-streaming chat completion with optional JSON schema response.
    async fn chat_completion(
        &self,
        messages: &[LlmMessage],
        json_schema: Option<serde_json::Value>,
    ) -> Result<String, LlmProviderError>;
}

/// Collect a full assistant reply from a streaming chat completion.
///
/// `OpenRouter` and some OpenAI-compatible models respond reliably to streaming
/// requests but may hang or exceed budgets on non-streaming `chat().create()`.
pub async fn collect_chat_completion(
    provider: &dyn LlmProvider,
    messages: &[LlmMessage],
) -> Result<String, LlmProviderError> {
    let mut stream = provider.create_chat_stream(messages, &[]).await?;
    let mut content = String::new();
    while let Some(chunk_res) = stream.next().await {
        let chunk = chunk_res?;
        if let Some(delta) = chunk.text_delta {
            content.push_str(&delta);
        }
    }
    Ok(content)
}

/// Distinguishes embedding use cases. Providers may apply different prefixes
/// or chunking strategies per kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EmbeddingKind {
    /// Concise tool or document summary text.
    Summary,
    /// Full description text (often long).
    Description,
    /// One embedding per capability / action within a mega-tool.
    Capability,
    /// One embedding per worked example.
    Example,
    /// Negative-keyword text (used for soft penalties in Tool RAG).
    Negative,
    /// User query, may use a different prefix than documents.
    Query,
    /// Hypothetical document generated by `HyDE`.
    Hyde,
}

/// Errors raised by embedding providers. Wraps transport, provider, and
/// local-init errors in a single enum so call sites can use a typed error
/// instead of `String`. Consumers should match on the variant rather than
/// parsing the message.
#[derive(Debug, thiserror::Error)]
pub enum EmbeddingError {
    /// The embedding model failed to initialize (e.g. GGUF load error).
    /// Distinct from `Provider`, which is for transport / API errors.
    #[error("embedding init error: {0}")]
    Init(String),
    /// The provider returned a malformed or empty response, or a transport
    /// error (HTTP 4xx/5xx, network failure) prevented the request.
    #[error("embedding provider error: {0}")]
    Provider(String),
    /// The supplied text is empty or whitespace-only. We
    /// refuse to produce an embedding for it because
    /// every implementation would either return the
    /// zero vector (which has undefined cosine
    /// similarity and silently pollutes the store) or
    /// fall back to a placeholder that does not
    /// represent the input.
    #[error("empty or whitespace-only input; cannot produce a meaningful embedding")]
    EmptyInput,
    /// Batch response length or per-vector dimensionality does not match
    /// the request / provider contract.
    #[error("embedding dimension or batch mismatch: {0}")]
    DimensionMismatch(String),
}

/// Trait for generating vector embeddings from text (used by memory search and Tool RAG).
///
/// The only embedding operation on this trait is [`embed_batch`]. Single-text and
/// query helpers are free functions ([`embed`], [`embed_query`]) that call
/// batch. `HyDE` and rerank live in pipeline helpers (`ene_ai::hybrid`,
/// tool-host RAG), not on this trait.
#[async_trait]
pub trait EmbeddingProvider: Send + Sync {
    /// Batch embed. Implementations should saturate hardware (thread pool for
    /// GGUF, concurrent HTTP for cloud). Output order must match `items`.
    /// An empty `items` slice returns an empty `Vec`.
    async fn embed_batch(
        &self,
        items: &[(&str, EmbeddingKind)],
    ) -> Result<Vec<Vec<f32>>, EmbeddingError>;

    /// The dimensionality of the embedding vectors produced by this provider.
    fn dimensions(&self) -> usize;
    /// A human-readable name identifying the embedding model.
    fn model_name(&self) -> &str;
}

/// Embed a single piece of text via [`EmbeddingProvider::embed_batch`].
pub async fn embed<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
    kind: EmbeddingKind,
) -> Result<Vec<f32>, EmbeddingError> {
    let mut out = provider.embed_batch(&[(text, kind)]).await?;
    out.pop().ok_or_else(|| {
        EmbeddingError::DimensionMismatch(
            "embed_batch returned empty result for a single-item request".into(),
        )
    })
}

/// Embed a query via [`embed`] with [`EmbeddingKind::Query`].
pub async fn embed_query<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
) -> Result<Vec<f32>, EmbeddingError> {
    embed(provider, text, EmbeddingKind::Query).await
}

/// Cosine similarity between two vectors. Returns 0.0 for empty or norm-zero
/// inputs. Both vectors must have the same length for a meaningful result.
#[must_use]
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.is_empty() || b.is_empty() || a.len() != b.len() {
        return 0.0;
    }
    let mut dot = 0.0_f64;
    let mut na = 0.0_f64;
    let mut nb = 0.0_f64;
    for (x, y) in a.iter().zip(b.iter()) {
        dot = f64::from(*x).mul_add(f64::from(*y), dot);
        na += f64::from(*x).powi(2);
        nb += f64::from(*y).powi(2);
    }
    let denom = (na * nb).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        (dot / denom) as f32
    }
}

/// Factory trait to build specific `LlmProvider` instances from workspace configs.
pub trait LlmProviderFactory: Send + Sync {
    /// The unique name of the provider this factory produces.
    fn provider_name(&self) -> &str;

    /// Instantiates the provider based on current `EneConfig` settings.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError>;
}

/// Global registry of `LlmProviderFactory` implementations.
pub struct LlmProviderRegistry {
    factories: Mutex<HashMap<String, Arc<dyn LlmProviderFactory>>>,
}

impl LlmProviderRegistry {
    /// Returns the static, thread-safe global registry instance.
    fn global() -> &'static Self {
        static REGISTRY: OnceLock<LlmProviderRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| Self {
            factories: Mutex::new(HashMap::new()),
        })
    }

    /// Registers a new provider factory.
    pub fn register(factory: Arc<dyn LlmProviderFactory>) {
        let name = factory.provider_name().to_string();
        if let Ok(mut guard) = Self::global().factories.lock() {
            guard.insert(name, factory);
        }
    }

    /// Tries to instantiate a provider by name using the registered factories.
    pub fn create_provider(
        name: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError> {
        let factory = {
            if let Ok(guard) = Self::global().factories.lock() {
                guard.get(name).cloned()
            } else {
                None
            }
        };

        match factory {
            Some(f) => f.create_provider(config),
            None => Err(LlmProviderError::Provider(format!(
                "No LlmProviderFactory registered for provider name: '{name}'"
            ))),
        }
    }
}

#[cfg(test)]
#[expect(
    clippy::float_cmp,
    clippy::indexing_slicing,
    reason = "tests assert exact float equality and fixed mock embedder indices"
)]
mod tests {
    use super::*;

    struct MockEmbedder {
        dims: usize,
    }

    #[async_trait]
    impl EmbeddingProvider for MockEmbedder {
        async fn embed_batch(
            &self,
            items: &[(&str, EmbeddingKind)],
        ) -> Result<Vec<Vec<f32>>, EmbeddingError> {
            let mut out = Vec::with_capacity(items.len());
            for (text, _) in items {
                if text.trim().is_empty() {
                    return Err(EmbeddingError::EmptyInput);
                }
                let mut v = vec![0.0_f32; self.dims];
                if let (Some(slot), Some(c)) = (v.first_mut(), text.chars().next()) {
                    *slot = f32::from(c as u8);
                }
                out.push(v);
            }
            Ok(out)
        }

        fn dimensions(&self) -> usize {
            self.dims
        }

        fn model_name(&self) -> &'static str {
            "mock"
        }
    }

    #[tokio::test]
    async fn embed_batch_preserves_order_and_empty() {
        let p = MockEmbedder { dims: 4 };
        assert!(p.embed_batch(&[]).await.unwrap().is_empty());
        let items = [
            ("alpha", EmbeddingKind::Query),
            ("beta", EmbeddingKind::Summary),
        ];
        let out = p.embed_batch(&items).await.unwrap();
        assert_eq!(out.len(), 2);
        assert_eq!(out[0][0], f32::from(b'a'));
        assert_eq!(out[1][0], f32::from(b'b'));
    }

    #[tokio::test]
    async fn embed_and_embed_query_wrappers() {
        let p = MockEmbedder { dims: 3 };
        let v = embed(&p, "hello", EmbeddingKind::Summary).await.unwrap();
        assert_eq!(v.len(), 3);
        let q = embed_query(&p, "hello").await.unwrap();
        assert_eq!(q.len(), 3);
        assert!(matches!(
            embed(&p, "   ", EmbeddingKind::Query).await,
            Err(EmbeddingError::EmptyInput)
        ));
    }

    #[test]
    fn cosine_similarity_dimension_mismatch_is_zero() {
        assert_eq!(cosine_similarity(&[1.0, 0.0], &[1.0]), 0.0);
        assert_eq!(cosine_similarity(&[], &[1.0]), 0.0);
    }
}
