use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::pin::Pin;
use std::sync::Arc;
use tokio_stream::{Stream, StreamExt};

use crate::config::TaskRef;
use crate::error::LlmProviderError;
use crate::message::{LlmCompletion, LlmMessage, LlmResponseChunk};

#[async_trait]
pub trait LlmProvider: Send + Sync {
    fn name(&self) -> &str;

    /// Context window the backend advertises for the active model, in tokens.
    ///
    /// `None` means the backend does not report a limit — an in-process
    /// provider that does not know its own window, or an older plugin binary
    /// that omits `LlmProviderSpec.context_window`. Callers reconcile this with
    /// any operator override via [`crate::context_window::effective_window`],
    /// which falls back to [`crate::context_window::DEFAULT_CONTEXT_WINDOW`]
    /// when neither source names a limit.
    fn context_window(&self) -> Option<u32> {
        None
    }

    async fn create_chat_stream(
        &self,
        messages: &[LlmMessage],
        tools: &[ene_plugin_proto::ToolSpec],
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<LlmResponseChunk, LlmProviderError>> + Send>>,
        LlmProviderError,
    >;

    /// Returns an [`LlmCompletion`] carrying the assistant text plus any token
    /// usage the provider reported; `usage` is `None` when the provider
    /// does not report it.
    async fn chat_completion(
        &self,
        messages: &[LlmMessage],
        json_schema: Option<serde_json::Value>,
    ) -> Result<LlmCompletion, LlmProviderError>;

    /// `OpenRouter` and some OpenAI-compatible models respond reliably to streaming
    /// requests but may hang or exceed budgets on non-streaming `chat().create()`.
    ///
    /// Returns an [`LlmCompletion`]: the concatenated text plus any usage the
    /// provider attached to the stream's final chunk.
    async fn collect_stream_completion(
        &self,
        messages: &[LlmMessage],
    ) -> Result<LlmCompletion, LlmProviderError> {
        let mut stream = self.create_chat_stream(messages, &[]).await?;
        let mut content = String::new();
        let mut usage = None;
        while let Some(chunk_res) = stream.next().await {
            let chunk = chunk_res?;
            if let Some(delta) = chunk.text_delta {
                content.push_str(&delta);
            }
            if chunk.usage.is_some() {
                usage = chunk.usage;
            }
        }
        Ok(LlmCompletion {
            text: content,
            usage,
        })
    }
}

/// Distinguishes embedding use cases. Providers may apply different prefixes
/// or chunking strategies per kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EmbeddingKind {
    Summary,
    Description,
    /// One embedding per capability / action within a mega-tool.
    Capability,
    Example,
    /// Negative-keyword text (used for soft penalties in Tool RAG).
    Negative,
    Query,
    /// Hypothetical document generated by `HyDE`.
    Hyde,
}

/// Errors raised by embedding providers. Wraps transport, provider, and
/// local-init errors in a single enum so call sites can use a typed error
/// instead of `String`. Consumers should match on the variant rather than
/// parsing the message.
#[derive(Debug, thiserror::Error)]
pub enum EmbeddingError {
    /// The embedding model failed to initialize (e.g. GGUF load error).
    /// Distinct from `Provider`, which is for transport / API errors.
    #[error("embedding init error: {0}")]
    Init(String),
    /// The provider returned a malformed or empty response, or a transport
    /// error (HTTP 4xx/5xx, network failure) prevented the request.
    #[error("embedding provider error: {0}")]
    Provider(String),
    /// An upstream plugin rejected the request with a non-transport error
    /// (e.g. authentication or rate-limit after the plugin exhausted its own
    /// retry budget). Terminal from the host's perspective — the plugin
    /// already retried — so the host policy must not re-issue the call.
    #[error("embedding provider rejected the request: {0}")]
    Other(String),
    /// The supplied text is empty or whitespace-only. We
    /// refuse to produce an embedding for it because
    /// every implementation would either return the
    /// zero vector (which has undefined cosine
    /// similarity and silently pollutes the store) or
    /// fall back to a placeholder that does not
    /// represent the input.
    #[error("empty or whitespace-only input; cannot produce a meaningful embedding")]
    EmptyInput,
    /// Batch response length or per-vector dimensionality does not match
    /// the request / provider contract.
    #[error("embedding dimension or batch mismatch: {0}")]
    DimensionMismatch(String),
}

impl EmbeddingError {
    /// Whether this error is transient and may succeed on retry.
    ///
    /// Transport / API failures (`Provider`) are retryable; init, other
    /// provider rejections, empty-input, and dimension-mismatch errors are
    /// deterministic and not retried.
    #[must_use]
    pub const fn is_retryable(&self) -> bool {
        matches!(self, Self::Provider(_))
    }
}

/// The only embedding operation on this trait is [`embed_batch`]. Single-text and
/// query helpers are free functions ([`embed`], [`embed_query`]) that call
/// batch. `HyDE` and rerank live in pipeline helpers (`ene_rag::tool::hybrid`),
/// not on this trait.
#[async_trait]
pub trait EmbeddingProvider: Send + Sync {
    /// Implementations should saturate hardware (thread pool for GGUF,
    /// concurrent HTTP for cloud). Output order must match `items`. An empty
    /// `items` slice returns an empty `Vec`.
    async fn embed_batch(
        &self,
        items: &[(&str, EmbeddingKind)],
    ) -> Result<Vec<Vec<f32>>, EmbeddingError>;

    fn dimensions(&self) -> usize;
    fn model_name(&self) -> &str;
}

pub async fn embed<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
    kind: EmbeddingKind,
) -> Result<Vec<f32>, EmbeddingError> {
    let mut out = provider.embed_batch(&[(text, kind)]).await?;
    out.pop().ok_or_else(|| {
        EmbeddingError::DimensionMismatch(
            "embed_batch returned empty result for a single-item request".into(),
        )
    })
}

pub async fn embed_query<P: EmbeddingProvider + ?Sized>(
    provider: &P,
    text: &str,
) -> Result<Vec<f32>, EmbeddingError> {
    embed(provider, text, EmbeddingKind::Query).await
}

/// Returns 0.0 for empty or norm-zero inputs. Both vectors must have the same
/// length for a meaningful result.
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.is_empty() || b.is_empty() {
        return 0.0;
    }
    if a.len() != b.len() {
        tracing::warn!(
            component = "cosine_similarity",
            a_len = a.len(),
            b_len = b.len(),
            "dimension mismatch; returning 0.0"
        );
        return 0.0;
    }
    let mut dot = 0.0_f64;
    let mut na = 0.0_f64;
    let mut nb = 0.0_f64;
    for (x, y) in a.iter().zip(b.iter()) {
        dot = f64::from(*x).mul_add(f64::from(*y), dot);
        na += f64::from(*x).powi(2);
        nb += f64::from(*y).powi(2);
    }
    let denom = (na * nb).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        (dot / denom) as f32
    }
}

pub trait LlmProviderFactory: Send + Sync {
    fn provider_name(&self) -> &str;

    /// `task` carries the cognitive task's routing entry — its `model` and
    /// `max_tokens` overrides in particular — so providers can honor
    /// task-specific configuration (e.g. `Classifier` or `Proactive`) instead
    /// of silently falling back to the `tasks.chat` defaults.
    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
        task: &TaskRef,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError>;
}

/// Plugin-provided embedding backends implement this on the host side
/// (`ene-plugin-host`'s `IpcEmbeddingProviderFactory`); the plugin host
/// registry looks factories up by provider kind.
pub trait EmbeddingProviderFactory: Send + Sync {
    fn provider_kind(&self) -> &str;

    fn create_embedding_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Arc<dyn EmbeddingProvider>, EmbeddingError>;
}

/// Host-side provider factory lookup used by task routing and failover.
///
/// Implemented by the plugin host manager (the single provider registry:
/// `ene-plugin-host`'s `PluginHostManager`), and by test stubs. Provider
/// creation never consults a process-global registry anymore — callers hold
/// the current host (or a stub) and query it directly.
#[async_trait]
pub trait ProviderHost: Send + Sync {
    async fn create_llm_provider(
        &self,
        kind: &str,
        config: &ene_config::EneConfig,
        task: &TaskRef,
    ) -> Result<Box<dyn LlmProvider>, LlmProviderError>;

    async fn create_embedding_provider(
        &self,
        kind: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Arc<dyn EmbeddingProvider>, EmbeddingError>;

    async fn create_tts_provider(
        &self,
        kind: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn TtsProvider>, AudioProviderError>;

    async fn create_stt_provider(
        &self,
        kind: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn SttProvider>, AudioProviderError>;

    async fn create_vad_engine(
        &self,
        kind: &str,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn VadEngine>, AudioProviderError>;
}

#[cfg(test)]
#[expect(
    clippy::float_cmp,
    clippy::indexing_slicing,
    reason = "tests assert exact float equality and fixed mock embedder indices"
)]
mod tests {
    use super::*;

    struct MockEmbedder {
        dims: usize,
    }

    #[async_trait]
    impl EmbeddingProvider for MockEmbedder {
        async fn embed_batch(
            &self,
            items: &[(&str, EmbeddingKind)],
        ) -> Result<Vec<Vec<f32>>, EmbeddingError> {
            let mut out = Vec::with_capacity(items.len());
            for (text, _) in items {
                if text.trim().is_empty() {
                    return Err(EmbeddingError::EmptyInput);
                }
                let mut v = vec![0.0_f32; self.dims];
                if let (Some(slot), Some(c)) = (v.first_mut(), text.chars().next()) {
                    *slot = f32::from(c as u8);
                }
                out.push(v);
            }
            Ok(out)
        }

        fn dimensions(&self) -> usize {
            self.dims
        }

        fn model_name(&self) -> &'static str {
            "mock"
        }
    }

    #[tokio::test]
    async fn embed_batch_preserves_order_and_empty() {
        let p = MockEmbedder { dims: 4 };
        assert!(p.embed_batch(&[]).await.unwrap().is_empty());
        let items = [
            ("alpha", EmbeddingKind::Query),
            ("beta", EmbeddingKind::Summary),
        ];
        let out = p.embed_batch(&items).await.unwrap();
        assert_eq!(out.len(), 2);
        assert_eq!(out[0][0], f32::from(b'a'));
        assert_eq!(out[1][0], f32::from(b'b'));
    }

    #[tokio::test]
    async fn embed_and_embed_query_wrappers() {
        let p = MockEmbedder { dims: 3 };
        let v = embed(&p, "hello", EmbeddingKind::Summary).await.unwrap();
        assert_eq!(v.len(), 3);
        let q = embed_query(&p, "hello").await.unwrap();
        assert_eq!(q.len(), 3);
        assert!(matches!(
            embed(&p, "   ", EmbeddingKind::Query).await,
            Err(EmbeddingError::EmptyInput)
        ));
    }

    #[test]
    fn cosine_similarity_dimension_mismatch_is_zero() {
        assert_eq!(cosine_similarity(&[1.0, 0.0], &[1.0]), 0.0);
        assert_eq!(cosine_similarity(&[], &[1.0]), 0.0);
    }
}

#[derive(Debug, thiserror::Error)]
pub enum AudioProviderError {
    /// The audio backend failed to initialize (model load, device open).
    #[error("audio init error: {0}")]
    Init(String),
    /// The provider encountered an error during synthesis or transcription.
    #[error("audio provider error: {0}")]
    Provider(String),
    /// The requested audio format or sample rate is not supported.
    #[error("unsupported audio format: {0}")]
    UnsupportedFormat(String),
    #[error("audio operation timed out")]
    Timeout,
    /// An underlying I/O operation failed (file read, dylib load).
    #[error("audio I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// A local engine's bounded job queue was full
    /// (`ene_infer::EngineError::Busy`). Enqueue contention only — the
    /// engine itself is fine.
    #[error("engine busy: queue depth {queue_depth} exceeded")]
    Busy { queue_depth: usize },
    /// A local engine's job was cancelled (`ene_infer::EngineError::Cancelled`),
    /// either by an explicit cancellation or because the caller went away.
    #[error("local engine job cancelled")]
    Cancelled,
    /// An audio payload (e.g. a plugin's synthesized WAV) exceeded the
    /// provider's size cap and was rejected before full allocation.
    #[error("audio payload too large: {actual} bytes exceeds the {max_bytes}-byte limit")]
    PayloadTooLarge { max_bytes: usize, actual: usize },
}

impl AudioProviderError {
    /// Whether this error is transient and may succeed on retry.
    ///
    /// `Busy` and `Timeout` are retryable, mirroring
    /// `ene_infer::EngineError::is_retryable`. `Cancelled` reflects caller
    /// intent, not engine health, so it is conservatively reported as not
    /// retryable. All other variants are deterministic or provider-specific
    /// and not retried.
    #[must_use]
    pub const fn is_retryable(&self) -> bool {
        matches!(self, Self::Busy { .. } | Self::Timeout)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct TtsChunk {
    /// Interleaved mono PCM samples normalized to `[-1.0, 1.0]`.
    pub pcm: Vec<f32>,
    /// Sample rate in Hz (e.g. 24000).
    pub sample_rate: u32,
}

#[async_trait]
pub trait TtsProvider: Send + Sync {
    fn name(&self) -> &str;

    async fn synthesize_stream(
        &self,
        text: &str,
    ) -> Result<
        Pin<Box<dyn Stream<Item = Result<TtsChunk, AudioProviderError>> + Send>>,
        AudioProviderError,
    >;

    async fn synthesize(&self, text: &str) -> Result<Vec<TtsChunk>, AudioProviderError> {
        let mut stream = self.synthesize_stream(text).await?;
        let mut chunks = Vec::new();
        while let Some(chunk) = stream.next().await {
            chunks.push(chunk?);
        }
        Ok(chunks)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct SttResult {
    pub text: String,
    pub language: Option<String>,
    /// Duration of the transcribed audio in seconds.
    pub duration_secs: f32,
}

#[async_trait]
pub trait SttProvider: Send + Sync {
    fn name(&self) -> &str;

    async fn transcribe(
        &self,
        pcm: &[f32],
        sample_rate: u32,
    ) -> Result<SttResult, AudioProviderError>;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VadEvent {
    SpeechStart,
    SpeechContinue,
    SpeechEnd,
    Silence,
}

/// Trait implemented by voice activity detection engines.
///
/// Engines are stateful (`&mut self`) and process fixed-size PCM chunks
/// sequentially. Not `Sync` because internal state is mutated per chunk.
///
/// # Frame-size contract
///
/// Each engine consumes frames of a fixed length reported by
/// [`frame_size`](Self::frame_size) (e.g. Silero VAD expects 512 samples at
/// 16 kHz / 32 ms). Callers must accumulate microphone PCM into exactly
/// [`frame_size`](Self::frame_size) samples before each
/// [`process_chunk`](Self::process_chunk) call. Passing a slice of any other
/// length is a programming error and [`process_chunk`](Self::process_chunk)
/// returns [`AudioProviderError::Provider`].
pub trait VadEngine: Send {
    fn frame_size(&self) -> usize;

    /// # Errors
    ///
    /// Returns [`AudioProviderError::Provider`] when `pcm.len()` does not equal
    /// [`frame_size`](Self::frame_size), or when the underlying inference step
    /// fails repeatedly (see the engine implementation for escalation policy).
    fn process_chunk(&mut self, pcm: &[f32]) -> Result<VadEvent, AudioProviderError>;

    fn reset(&mut self);

    fn name(&self) -> &str;
}

pub trait TtsProviderFactory: Send + Sync {
    fn provider_name(&self) -> &str;

    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn TtsProvider>, AudioProviderError>;
}

pub trait SttProviderFactory: Send + Sync {
    fn provider_name(&self) -> &str;

    fn create_provider(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn SttProvider>, AudioProviderError>;
}

pub trait VadFactory: Send + Sync {
    fn provider_name(&self) -> &str;

    fn create_engine(
        &self,
        config: &ene_config::EneConfig,
    ) -> Result<Box<dyn VadEngine>, AudioProviderError>;
}

#[cfg(test)]
mod audio_tests {
    use super::*;

    #[test]
    fn io_error_converts_via_from() {
        let io_err = std::io::Error::new(std::io::ErrorKind::NotFound, "missing");
        let err: AudioProviderError = io_err.into();
        assert!(matches!(err, AudioProviderError::Io(_)));
    }
}
