use std::env;
use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let ftl_path = Path::new(&manifest_dir).join("i18n/en-US/ene_desktop.ftl");

    // Tell Cargo to rerun this build script if the translation file changes
    println!("cargo:rerun-if-changed={}", ftl_path.display());

    let content = fs::read_to_string(&ftl_path)?;

    let mut keys = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        // Skip comments and empty lines
        if trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }

        // Match keys. FTL keys look like: key-name = value
        if let Some(pos) = trimmed.find('=') {
            let key = trimmed[..pos].trim();
            if !key.is_empty() {
                keys.push(key.to_string());
            }
        }
    }

    // Sort and dedup to be deterministic and safe
    keys.sort();
    keys.dedup();

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n\n");

    for key in keys {
        let rust_name = key.replace('-', "_");

        // Ensure name is a valid Rust identifier (e.g. not a keyword)
        let sanitized_name = if rust_name == "type"
            || rust_name == "fn"
            || rust_name == "struct"
            || rust_name == "enum"
            || rust_name == "impl"
            || rust_name == "match"
            || rust_name == "use"
            || rust_name == "pub"
        {
            format!("{}_", rust_name)
        } else {
            rust_name
        };

        code.push_str(&format!(
            "#[allow(dead_code)]\n\
             #[must_use]\n\
             pub fn {sanitized_name}() -> String {{\n\
                 i18n_embed_fl::fl!(loader(), \"{key}\")\n\
             }}\n\n",
            sanitized_name = sanitized_name,
            key = key
        ));
    }

    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("i18n_keys.rs");
    fs::write(&dest_path, code)?;
    Ok(())
}
