use ene_store::{AffectAnnotation, MemoryKind};
use serde::{Deserialize, Serialize};

/// A query plan generated by the recall planner.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecallPlan {
    /// Short normalized topic for the current turn.
    pub current_topic: String,
    /// Natural-language queries aimed at semantic facts, preferences, and lore.
    pub semantic_queries: Vec<String>,
    /// Natural-language queries aimed at past events and previous turns.
    pub episodic_queries: Vec<String>,
    /// Memory kinds that should be included in the candidate search.
    pub required_kinds: Vec<MemoryKind>,
    /// Character/user recall scope.
    pub scope: RecallScopeFilter,
    /// Token and result-count budget hints.
    pub budget: RecallBudgetHints,
    /// Hybrid-search compatible hints.
    pub search: RecallSearchHints,
    /// Whether the downstream recall executor should run `HyDE` expansion.
    pub use_hyde: bool,
}

/// Scope filter attached to a recall plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecallScopeFilter {
    /// Character identifier.
    pub character_id: String,
    /// Optional user identifier.
    pub user_id: Option<String>,
}

/// Budget hints for recalled-memory prompt sections.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecallBudgetHints {
    /// Token budget for recalled typed memories.
    pub memory_budget_tokens: usize,
    /// Token budget for semantic character/lorebook memory.
    pub semantic_budget_tokens: usize,
    /// Maximum number of memory results requested by the plan.
    pub result_limit: usize,
}

/// Search options that map onto `ene_store::Query`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecallSearchHints {
    /// Primary natural-language query for lexical and vector search.
    pub primary_query_text: String,
    /// Minimum vector similarity for vector-sourced candidates.
    pub similarity_threshold: f32,
    /// Minimum hybrid total score required to return a result.
    pub min_score: f32,
    /// Half-life in days for recency decay.
    pub decay_half_life_days: f64,
    /// Optional affect annotation for emotional-match scoring.
    pub query_affect: Option<AffectAnnotation>,
}
