use ene_api::{JobView, MemoryView, PluginView, ProviderAssetView, ScheduleView};

pub enum AsyncOutcome {
    SendMessage(Result<(), String>),
    BargeIn(Result<(), String>),
    CancelTurn(Result<(), String>),
    Approval(Result<(), String>),
    Listen {
        generation: u64,
        result: Result<(), String>,
    },
    RefreshHistory(Result<ene_api::HistoryResponse, String>),
    SaveLocalSettings(Result<(), String>),
    LoadCoreSettings(Result<String, String>),
    ApplyCoreSettings(Result<(), String>),
    ListMemories(Result<Vec<MemoryView>, String>),
    ListPendingMemories(Result<Vec<MemoryView>, String>),
    ResolveMemory {
        id: String,
        result: Result<(), String>,
    },
    DeleteMemory {
        id: String,
        result: Result<(), String>,
    },
    CompleteMemory {
        id: String,
        result: Result<(), String>,
    },
    LoadSoul(Result<ene_api::SoulView, String>),
    PatchBody(Result<ene_api::SoulView, String>),
    ImportCharacter(Result<ene_api::CharacterView, String>),
    ActivateCharacter(Result<ene_api::CharacterView, String>),
    ListCharacters(Result<Vec<ene_api::CharacterView>, String>),
    ListOccupants(Result<Vec<ene_api::OccupantView>, String>),
    ListJobs(Result<(Vec<JobView>, Vec<ScheduleView>), String>),
    CancelJob {
        id: String,
        result: Result<(), String>,
    },
    ToggleSchedule {
        id: String,
        enabled: bool,
        result: Result<(), String>,
    },
    ListPlugins(Result<Vec<PluginView>, String>),
    RestartPlugin {
        id: String,
        result: Result<(), String>,
    },
    LoadPluginConfig {
        id: String,
        result: Result<ene_api::PluginConfigView, String>,
    },
    ValidatePluginConfig(Result<ene_api::PluginConfigValidateView, String>),
    ApplyPluginConfig(Result<ene_api::PluginConfigValidateView, String>),
    PluginConfigOptions(Result<ene_api::PluginConfigOptionsView, String>),
    ListProviderAssets(Result<Vec<ProviderAssetView>, String>),
    InstallProviderAsset {
        asset_id: String,
        result: Result<String, String>,
    },
    ProviderAssetInstallStatus {
        asset_id: String,
        result: Result<ene_api::ProviderAssetInstallStatusResponse, String>,
    },
    SetActiveProviderAsset {
        asset_id: String,
        result: Result<(), String>,
    },
    ListProviderModels(Result<(Vec<String>, Option<String>), String>),
    LoadMcp(Result<String, String>),
    SaveMcp(Result<(), String>),
    MicClaim(Result<bool, String>),
    SpeakerClaim(Result<String, String>),
    NotifyClaim(Result<(), String>),
    Health(Result<ene_api::Health, String>),
    Usage(Result<ene_api::UsageView, String>),
    Backup(Result<(String, String), String>),
    Restore(Result<(), String>),
    DiagSpans(Result<Vec<ene_api::SpanView>, String>),
    LoadSchema(Result<String, String>),
    ListApprovals(Result<Vec<ene_api::ApprovalView>, String>),
    ReloadAvatar,
    ExportCharacter(Result<(), String>),
    ForkSession(Result<String, String>),
    CompactSession(Result<String, String>),
    ExportSession(Result<(), String>),
}
