[package]
name = "ene-ai-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
async-openai = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
indexmap = { workspace = true }
async-stream = "0.3"
async-trait = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
ene-config = { path = "../ene-config" }
ene-embedding = { path = "../ene-embedding" }
ene-memory = { path = "../ene-memory" }
ene-session = { path = "../ene-session" }
ene-tool-host = { path = "../ene-tool-host" }
