[package]
name = "ene-config"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
dirs = "6"
indexmap = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
ene-tool-proto = { workspace = true }
